=encoding utf8

=head1 NAME

SQL-Ledger - open source ERP and accounting system

=head1 DESCRIPTION

L<SQL-Ledger|https://github.com/Tekki/sql-ledger> is a web-based open source ERP
and accounting platform that delivers all the essential tools for order
management, invoicing, and accounting.

=head1 REFERENCE

=head2 bin/mozilla - Frontend

=over

=item * L<binE<sol>mozillaE<sol>aa.pl|bin::mozilla::aa.pl> - AR / AP

=item * L<binE<sol>mozillaE<sol>admin.pl|bin::mozilla::admin.pl> - Setup module

=item * L<binE<sol>mozillaE<sol>am.pl|bin::mozilla::am.pl> - Administration

=item * L<binE<sol>mozillaE<sol>ap.pl|bin::mozilla::ap.pl> - Accounts Payable

=item * L<binE<sol>mozillaE<sol>api.pl|bin::mozilla::api.pl> - JSON API

=item * L<binE<sol>mozillaE<sol>ar.pl|bin::mozilla::ar.pl> - Accounts Receivable

=item * L<binE<sol>mozillaE<sol>arap.pl|bin::mozilla::arap.pl> - Common routines for gl, ar, ap, is, ir, oe

=item * L<binE<sol>mozillaE<sol>arapprn.pl|bin::mozilla::arapprn.pl> - Printing routines for ar, ap

=item * L<binE<sol>mozillaE<sol>bp.pl|bin::mozilla::bp.pl> - Batch printing

=item * L<binE<sol>mozillaE<sol>ca.pl|bin::mozilla::ca.pl> - Module for Chart of Accounts, Income Statement and Balance Sheet

=item * L<binE<sol>mozillaE<sol>cm.pl|bin::mozilla::cm.pl> - Attach Reference Documents to transactions

=item * L<binE<sol>mozillaE<sol>cp.pl|bin::mozilla::cp.pl> - Payment module

=item * L<binE<sol>mozillaE<sol>ct.pl|bin::mozilla::ct.pl> - Customer/vendor module

=item * L<binE<sol>mozillaE<sol>gl.pl|bin::mozilla::gl.pl> - General Ledger

=item * L<binE<sol>mozillaE<sol>hr.pl|bin::mozilla::hr.pl> - Payroll module

=item * L<binE<sol>mozillaE<sol>ic.pl|bin::mozilla::ic.pl> - Inventory Control module

=item * L<binE<sol>mozillaE<sol>im.pl|bin::mozilla::im.pl> - Import/export

=item * L<binE<sol>mozillaE<sol>io.pl|bin::mozilla::io.pl> - Common routines used in is, ir, oe, ic

=item * L<binE<sol>mozillaE<sol>ir.pl|bin::mozilla::ir.pl> - Inventory received module

=item * L<binE<sol>mozillaE<sol>is.pl|bin::mozilla::is.pl> - Inventory invoicing module

=item * L<binE<sol>mozillaE<sol>jc.pl|bin::mozilla::jc.pl> - Job Costing module

=item * L<binE<sol>mozillaE<sol>js.pl|bin::mozilla::js.pl> - Routines to create Javascript functions

=item * L<binE<sol>mozillaE<sol>login.pl|bin::mozilla::login.pl> - Login frontend

=item * L<binE<sol>mozillaE<sol>menu.pl|bin::mozilla::menu.pl> - Two frame layout with refractured menu

=item * L<binE<sol>mozillaE<sol>oe.pl|bin::mozilla::oe.pl> - Order entry module

=item * L<binE<sol>mozillaE<sol>pe.pl|bin::mozilla::pe.pl> - Project/job administration

=item * L<binE<sol>mozillaE<sol>pos.pl|bin::mozilla::pos.pl> - POS

=item * L<binE<sol>mozillaE<sol>ps.pl|bin::mozilla::ps.pl> - Point of sale script

=item * L<binE<sol>mozillaE<sol>pw.pl|bin::mozilla::pw.pl> - Password dialog

=item * L<binE<sol>mozillaE<sol>rc.pl|bin::mozilla::rc.pl> - Account reconciliation module

=item * L<binE<sol>mozillaE<sol>rd.pl|bin::mozilla::rd.pl> - Reference Documents

=item * L<binE<sol>mozillaE<sol>rp.pl|bin::mozilla::rp.pl> - Module for preparing Income Statement and Balance Sheet

=item * L<binE<sol>mozillaE<sol>ru.pl|bin::mozilla::ru.pl> - Frontend for recently used objects

=item * L<binE<sol>mozillaE<sol>sm.pl|bin::mozilla::sm.pl> - Maintainance module

=item * L<binE<sol>mozillaE<sol>sr.pl|bin::mozilla::sr.pl> - Save reports

=item * L<binE<sol>mozillaE<sol>vr.pl|bin::mozilla::vr.pl> - Voucher/batch register

=item * L<binE<sol>mozillaE<sol>wlprinter.pl|bin::mozilla::wlprinter.pl> - Download and start WLprinter JAVA client

=back

=head2 SL - Backend

=over

=item * L<SL::AA> - AR/AP backend routines

=item * L<SL::ADR> - Address Validation

=item * L<SL::AM> - Administration module

=item * L<SL::API> - JSON API

=item * L<SL::BP> - Batch printing module backend routines

=item * L<SL::CA> - Chart of accounts

=item * L<SL::CP> - Check and receipt printing payment module backend routines

=item * L<SL::CT> - Backend code for customers and vendors

=item * L<SL::Form> - Request container and utilities

=item * L<SL::GL> - General ledger backend code

=item * L<SL::HR> - Backend code for human resources and payroll

=item * L<SL::IC> - Inventory Control backend

=item * L<SL::IM> - Import/Export module

=item * L<SL::IR> - Inventory received module

=item * L<SL::IS> - Inventory invoicing module

=item * L<SL::Inifile> - Routines to retrieve / manipulate win ini style files

=item * L<SL::JC> - Job Costing

=item * L<SL::JS> - Routines to create Javascript functions

=item * L<SL::Mailer> - Mailer package

=item * L<SL::Menu> - Routines for menu items

=item * L<SL::Num2text> - Default code for the Check package

=item * L<SL::OE> - Order entry module

=item * L<SL::OP> - Overpayment function

=item * L<SL::PE> - Project module

=item * L<SL::PM> - Price Matrix for IS, IR, OE

=item * L<SL::QRCode> - Generator and decoder for QR Codes

=item * L<SL::RC> - Account reconciliation routines

=item * L<SL::RD> - CMS backend routines

=item * L<SL::RP> - Backend code for reports

=item * L<SL::RU> - Backend for recently used objects

=item * L<SL::SM> - Module for reposting/deleting invoices

=item * L<SL::Spreadsheet> - Spreadsheet module

=item * L<SL::SPS> - Swiss Payment Standard

=item * L<SL::TOTP> - Time-based one-time passwords

=item * L<SL::User> - User related functions

=item * L<SL::VR> - Voucher/batch register backend routines

=back
