---
# starts a test and development environment
# with a PostgreSQL 15 container,
# SQL-Ledger at http://localhost/sql-ledger,
# Adminer at http://localhost:8080?pgsql=db,
# and pgAdmin at http://localhost:8085

version: '2.4'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_USER: sql-ledger
    volumes:
      - db:/var/lib/postgresql/data

  dbdamin:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      # change these settings or add a new user after the first login:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 8085:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build: .
    image: sql-ledger-test:0.15
    ports:
      - 80:80
    volumes:
      - ../.:/usr/local/apache2/htdocs/sql-ledger
      - gnupg:/usr/local/apache2/gnupg

volumes:
  db:
  gnupg:
  pgadmin:
