---
# starts a test environment
# with sql-ledger at http://localhost/sql-ledger
# and db admin at http://localhost:8080?pgsql=db

version: '2.4'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_USER: sql-ledger
    volumes:
      - db:/var/lib/postgresql/data

  dbdamin:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    environment:
      # change these settings or add a new user after the first login:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 8085:80
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build: .
    image: sql-ledger-test:0.13
    ports:
      - 80:80
    volumes:
      - ../.:/usr/local/apache2/htdocs/sql-ledger

volumes:
  db:
  pgadmin:
