#!/bin/sh
set -e

test -f sql-ledger.conf || cp sql-ledger.conf.default sql-ledger.conf
test -f wlprinter.conf || cp wlprinter.conf.default wlprinter.conf

sed -i -e 's|#$gpg.*|$gpg = "gpg --homedir /usr/local/apache2/gnupg --batch --yes";|' sql-ledger.conf

chown -R apache:apache images spool templates users

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/httpd/httpd.pid

exec httpd -DFOREGROUND
