---
# starts a test environment
# with sql-ledger at http://localhost/sql-ledger
# and db admin at http://localhost:8080?pgsql=db

version: '2.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sql-ledger
      POSTGRES_USER: sql-ledger
    volumes:
      - db:/var/lib/postgresql/data

  dbdamin:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - 8080:8080

  app:
    build: .
    image: sql-ledger-test:0.12
    ports:
      - 80:80
    volumes:
      - ../.:/usr/local/apache2/htdocs/sql-ledger

volumes:
  db:
