#!/bin/sh
set -e

test -f sql-ledger.conf || cp sql-ledger.conf.default sql-ledger.conf

sed -i -e 's|#$gpg.*|$gpg = "gpg --homedir /usr/local/apache2/gnupg --batch --yes";|' sql-ledger.conf

chown -R www-data:www-data images spool templates users

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND
