-- Czech chart of accounts
-- Tomas.Fencl@centrum.cz
--    Kompletní účtová osnova platná v roce 2001
--    Osnova má 2 místa pro tvorbu analytik
--
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1000', 'Dlouhodobý nehmotný majetek','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1100', 'Zřizovací výdaje','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1200', 'Nehmotné výsledky výzkumu a vývoje','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1300', 'Software','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1400', 'Ocenitelná práva','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1800', 'Drobný dlouhodobý nehmotný majetek','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1900', 'Ostatní dlouhodobý nehmotný majetek','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2000', 'Dlouhodobý Hmotný majetek odpisovaný','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2100', 'Stavby','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2200', 'Samostatné movité věci a soubory movitých věcí','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2500', 'Pěstitelské celky trvalých porostů','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2600', 'Základní stádo a tažná zvířata','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2800', 'Drobný dlouhodobý hmotný majetek','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2900', 'Ostatní dlouhodobý hmotný majetek','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3000', 'Dlouhodobý hmotný majetek neodpisovaný','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3100', 'Pozemky','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3200', 'Umělecká díla a sbírky','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4000', 'Pořízení dlouhodobého nehmotného a hmotného majetku','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4100', 'Pořízení dlouhodobého nehmotného majetku','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4200', 'Pořízení dlouhodobého hmotného majetku','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5000', 'Poskytnuté zálohy na dlouhodobý nehmotný a hmotný majetek','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5100', 'Poskytnuté zálohy na dlouhodobý nehmotný majetek','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5200', 'Poskytnuté zálohy na dlouhodobý hmotný majetek','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6000', 'Dlouhodobý finanční majetek','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6100', 'Podílové cenné papíry a vklady v podnicích s rozhodujícím','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6200', 'Podílové cenné papíry a vklady v podnicích s podstatným','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6300', 'Ostatní dlouhodobé cenné papíry a vklady','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6600', 'Půjčky podnikům ve skupině','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6700', 'Ostatní půjčky','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6900', 'Ostatní dlouhodobý finanční majetek','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7000', 'Oprávky k dlouhodobému nehmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7100', 'Oprávky ke zřizovacím výdajům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7200', 'Oprávky k nehmotným výsledkům výzkumu a vývoje','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7300', 'Oprávky k softwaru','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7400', 'Oprávky k ocenitelným právům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7800', 'Oprávky k drobnému dlouhodobému nehmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7900', 'Oprávky k ostatnímu dlouhodobému nehmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8000', 'Oprávky k dlouhodobému hmotnému majetku','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8100', 'Oprávky ke stavbám','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8200', 'Oprávky k samostatným movitým věcem a souborům movitých věcí','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8500', 'Oprávky k pěstitelským celkům trvalých porostů','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8600', 'Oprávky k základnímu stádu a tažným zvířatům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8800', 'Oprávky k drobnému dlouhodobému hmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8900', 'Oprávky k ostatnímu dlouhodobému hmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9000', 'Opravné položky k dlouhodobému majetku','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9100', 'Opravná položka k dlouhodobému nehmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9200', 'Opravná položka k dlouhodobému hmotnému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9300', 'Opravná položka k dlouhodobému nedokončenému nehmotnému','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9400', 'Opravná položka k dlouhodobému nedokončenému hmotnému','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9500', 'Opravná položka k poskytnutým zálohám','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9600', 'Opravná položka k dlouhodobému finančnímu majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9700', 'Opravná položka k nabytému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('9800', 'Oprávky k opravné položce k nabytému majetku','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('10000', 'Zásoby','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('11000', 'Materiál','H','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('11100', 'Pořízení materiálu','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('11200', 'Materiál na skladě','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('11900', 'Materiál na cestě','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12000', 'Zásoby vlastní výroby','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12100', 'Nedokončená výroba','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12200', 'Polotovary vlastní výroby','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12300', 'Výrobky','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12400', 'Zvířata','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('13000', 'Zboží','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('13100', 'Pořízení zboží','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('13200', 'Zboží na skladě a v prodejnách','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('13900', 'Zboží na cestě','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19000', 'Opravné položky k zásobám','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19100', 'Opravná položka k materiálu','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19200', 'Opravná položka k nedokončené výrobě','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19300', 'Opravná položka k polotovarům vlastní výroby','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19400', 'Opravná položka k výrobkům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19500', 'Opravná položka ke zvířatům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19600', 'Opravná položka ke zboží','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('20000', 'Finanční účty','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('21000', 'Peníze','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('21100', 'Pokladna','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('21300', 'Ceniny','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('22000', 'Účty v bankách','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('22100', 'Bankovní účty','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('22200', 'Bankovní účty klientů','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('23000', 'Běžné bankovní úvěry','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('23100', 'Krátkodobé bankovní úvěry','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('23200', 'Eskontní úvěry','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('24000', 'Jiné krátkodobé finanční výpomoci','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('24100', 'Emitované krátkodobé dluhopisy','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('24900', 'Ostatní krátkodobé finanční výpomoci','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25000', 'Krátkodobý finanční majetek','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25100', 'Majetkové cenné papíry','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25200', 'Vlastní akcie a vlastní obchodní podíly','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25300', 'Dlužné cenné papíry','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25500', 'Vlastní dluhopisy','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('25600', 'Ostatní cenné papíry','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('26000', 'Převody mezi finančními účty','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('26100', 'Peníze na cestě','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('29000', 'Opravné položky ke krátkodobému finančnímu majetku','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('29100', 'Opravná položka k majetkovým cenným papírům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('29300', 'Opravná položka k dlužným cenným papírům','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('30000', 'Zúčtovací vztahy','H','','H','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31000', 'Pohledávky','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31100', 'Odběratelé','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31200', 'Směnky k inkasu','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31300', 'Pohledávky za eskontované cenné papíry','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31400', 'Poskytnuté provozní zálohy','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31500', 'Ostatní pohledávky','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32000', 'Závazky','H','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32100', 'Dodavatelé','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32200', 'Směnky k úhradě','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32400', 'Přijaté zálohy','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32500', 'Ostatní závazky','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32600', ' Závazky vůči klientům','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('32700', ' Závazky vůči trhům','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33000', 'Zúčtování se zaměstnanci a institucemi','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33100', 'Zaměstnanci','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33300', 'Ostatní závazky vůči zaměstnancům','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33500', 'Pohledávky za zaměstnanci','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33600', 'Zúčtování s institucemi sociálního zabezpečení a zdravotního','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34000', 'Zúčtování daní a dotací','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34100', 'Daň z příjmů','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34200', 'Ostatní přímé daně','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34300', 'Daň z přidané hodnoty - zúčtování','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34311', 'DPH 5% vstup','A','','L','AP_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34312', 'DPH 22% vstup','A','','L','AP_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34321', 'DPH 5% výstup','A','','L','AR_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34322', 'DPH 22% výstup','A','','L','AR_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34500', 'Ostatní daně a poplatky','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34600', 'Dotace ze státního rozpočtu','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34700', 'Ostatní dotace','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35000', 'Pohledávky ke společníkům a sdružení','H','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35100', 'Pohledávky k podnikům ve skupině','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35300', 'Pohledávky za upsaný vlastní kapitál','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35400', 'Pohledávky za společníky při úhradě ztráty','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35500', 'Ostatní pohledávky za společníky','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35800', 'Pohledávky k účastníkům sdružení','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36000', 'Závazky ke společníkům a sdružení','H','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36100', 'Závazky k podnikům ve skupině','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36400', 'Závazky ke společníkům při rozdělování zisku','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36500', 'Ostatní závazky ke společníkům','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36600', 'Závazky ke společníkům a členům družstva ze závislé','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36700', 'Závazky z upsaných nesplacených cenných papírů a vkladů','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36800', 'Závazky k účastníkům sdružení','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37000', 'Jiné pohledávky a závazky','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37100', 'Odložená daňová pohledávka a závazek','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37300', 'Nakoupené opce','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37400', 'Prodané opce','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37500', 'Pohledávky z emitovaných dluhopisů','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37700', ' Zúčtování obchodů','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37800', 'Jiné pohledávky','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('37900', 'Jiné závazky','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38000', 'Přechodné účty aktiv a pasív','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38100', 'Náklady příštích období','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38200', 'Komplexní náklady příštích období','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38300', 'Výdaje příštích období','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38400', 'Výnosy příštích období','A','','L','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38500', 'Příjmy příštích období','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38600', 'Kursové rozdíly aktivní','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38700', 'Kursové rozdíly pasívní','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38800', 'Dohadné účty aktivní','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('38900', 'Dohadné účty pasívní','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('39000', 'Opravná položka k zúčtovacím vztahům a vnitřní zúčtování','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('39100', 'Opravná položka k pohledávkám','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('39500', 'Vnitřní zúčtování','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('39800', 'Spojovací účet při sdružení','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('40000', 'Kapitálové účty a dlouhodobé závazky','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41000', 'Základní kapitál a kapitálové fondy','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41100', 'Základní kapitál','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41200', 'Emisní ážio','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41300', 'Ostatní kapitálové fondy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41400', 'Oceňovací rozdíly z přecenění majetku a závazků','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42000', 'Fondy ze zisku a převedené hospodářské výsledky','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42100', 'Zákonný rezervní fond','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42200', 'Nedělitelný fond','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42300', 'Statutární fondy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42700', 'Ostatní fondy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42800', 'Nerozdělený zisk minulých let','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('42900', 'Neuhrazená ztráta minulých let','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('43000', 'Hospodářský výsledek','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('43100', 'Hospodářský výsledek ve schvalovacím řízení','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('45000', 'Rezervy','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('45100', 'Rezervy zákonné','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('45400', 'Rezerva na kursové ztráty','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('45900', 'Ostatní rezervy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('46000', 'Bankovní úvěry','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('46100', 'Bankovní úvěry','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47000', 'Dlouhodobé závazky','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47100', 'Dlouhodobé závazky k podnikům ve skupině','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47300', 'Emitované dluhopisy','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47400', 'Závazky z pronájmu','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47500', 'Dlouhodobé přijaté zálohy','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47800', 'Dlouhodobé směnky k úhradě','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('47900', 'Ostatní dlouhodobé závazky','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('49000', 'Individuální podnikatel','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('49100', 'Účet individuálního podnikatele','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50000', 'Spotřebované nákupy','A','','E','AP_amount:IC_COGS');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50100', 'Spotřeba materiálu','A','','E','AP_amount:IC_COGS');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50200', 'Spotřeba energie','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50300', 'Spotřeba ostatních neskladovatelných dodávek','A','','E','AP_amount:IC_COGS');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50400', 'Prodané zboží','A','','E','AP_amount:IC_COGS');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51000', 'Služby','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51100', 'Opravy a udržování','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51200', 'Cestovné','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51300', 'Náklady na reprezentaci','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51800', 'Ostatní služby','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52000', 'Osobní náklady','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52100', 'Mzdové náklady','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52200', 'Příjmy společníků a členů družstva ze závislé činnosti','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52300', 'Odměny členům orgánů společnosti a družstva','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52400', 'Zákonné sociální pojištění','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52500', 'Ostatní sociální pojištění','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52600', 'Sociální náklady individuálního podnikatele','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52700', 'Zákonné sociální náklady','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52800', 'Ostatní sociální náklady','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('53000', 'Daně a poplatky','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('53100', 'Daň silniční','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('53200', 'Daň z nemovitostí','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('53800', 'Ostatní daně a poplatky','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54000', 'Jiné provozní náklady','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54100', 'Zůstatková cena prodaného dlouhodobého nehmotného a hmotného','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54200', 'Prodaný materiál','A','','E','IC_COGS');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54300', 'Dary','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54400', 'Smluvní pokuty a úroky z prodlení','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54500', 'Ostatní pokuty a penále','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54600', 'Odpis pohledávky','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('54800', 'Ostatní provozní náklady','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55000', 'Odpisy, rezervy a opravné položky provozních nákladů','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55100', 'Odpisy dlouhodobého nehmotného a hmotného majetku','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55200', 'Tvorba zákonných rezerv','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55400', 'Tvorba ostatních rezerv','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55500', 'Zúčtování komplexních nákladů příštích období','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55700', 'Zúčtování oprávky k opravné položce k nabytému majetku','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55800', 'Tvorba zákonných opravných položek','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('55900', 'Tvorba opravných položek','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('56000', 'Finanční náklady','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('56100', 'Prodané cenné papíry a vklady','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('56200', 'Úroky','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('56300', 'Kursové ztráty','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('56800', 'Ostatní finanční náklady','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('57000', 'Rezervy a opravné položky finančních nákladů','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('57400', 'Tvorba rezerv','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('57900', 'Tvorba opravných položek','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58000', 'Mimořádné náklady','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58100', 'Náklady na změnu metody','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58200', 'Manka a škody','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58400', 'Tvorba rezerv','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58800', 'Ostatní mimořádné náklady','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('58900', 'Tvorba opravných položek','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59000', 'Daně z příjmů a převodové účty','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59100', 'Daň z příjmů z běžné činnosti - splatná','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59200', 'Daň z příjmů z běžné činnosti - odložená','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59300', 'Daň z příjmů z mimořádné činnosti - splatná','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59400', 'Daň z příjmů z mimořádné činnosti - odložené','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59500', 'Dodatečné odvody daně z příjmů','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59600', 'Převod podílu na hospodářském výsledku společníkům','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59700', 'Převod provozních nákladů','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('59800', 'Převod finančních nákladů','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('60000', 'Tržby za vlastní výkony a zboží','A','','I','AR_amount:IC_sale:IC_Income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('60100', 'Tržby za vlastní výrobky','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('60200', 'Tržby z prodeje služeb','A','','I','AR_amount:IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('60400', 'Tržby za zboží','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('61000', 'Změny stavu vnitropodnikových zásob','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('61100', 'Změna stavu nedokončené výroby','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('61200', 'Změna stavu polotovarů','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('61300', 'Změna stavu výrobků','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('61400', 'Změna stavu zvířat','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('62000', 'Aktivace','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('62100', 'Aktivace materiálu a zboží','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('62200', 'Aktivace vnitropodnikových služeb','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('62300', 'Aktivace dlouhodobého nehmotného majetku','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('62400', 'Aktivace dlouhodobého hmotného majetku','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64000', 'Jiné provozní výnosy.','A','','I','AR_amount:IC_sale:IC_Income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64100', 'Tržby z prodeje dlouhodobého nehmotného a hmotného majetku','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64200', 'Tržby z prodeje materiálu','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64400', 'Smluvní pokuty a úroky z prodlení','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64600', 'Výnosy z odepsaných pohledávek','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64800', 'Jiné provozní výnosy','A','','I','AR_amount:IC_sale:IC_Income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65000', 'Zúčtování rezerv a opravných položek provozních výnosů','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65200', 'Zúčtování zákonných rezerv','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65400', 'Zúčtování ostatních rezerv','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65500', 'Zúčtování komplexních nákladů příštích období','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65700', 'Zúčtování oprávky k opravné položce k nabytému majetku','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65800', 'Zúčtování zákonných opravných položek','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65900', 'Zúčtování opravných položek','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66000', 'Finanční výnosy','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66100', 'Tržby z prodeje cenných papírů a vkladů','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66200', 'Úroky','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66300', 'Kursové zisky','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66500', 'Výnosy z dlouhodobého finančního majetku','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66600', 'Výnosy z krátkodobého finančního majetku','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('66800', 'Ostatní finanční výnosy','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('67000', 'Zúčtování rezerv a opravných položek finančních výnosů','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('67400', 'Zúčtování rezerv','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('67900', 'Zúčtování opravných položek','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('68000', 'Mimořádné výnosy','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('68100', 'Výnosy ze změny metody','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('68400', 'Zúčtování rezerv','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('68800', 'Ostatní mimořádné výnosy','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('68900', 'Zúčtování opravných položek','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('69000', 'Převodové účty','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('69700', 'Převod provozních výnosů','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('69800', 'Převod finančních výnosů','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('70000', 'Účty rozvažné','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('70100', 'Počáteční účet rozvažný','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('70200', 'Konečný účet rozvažný','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('71000', 'Účet zisků a ztrát','A','','A','');
--
insert into tax (chart_id,rate) values ((select id from chart where accno = '34311'),0.05);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34312'),0.22);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34321'),0.05);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34322'),0.22);
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '13200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '60000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '50000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '99998'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '99999'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, prec) VALUES (1,'Kč',2);
INSERT INTO curr (rn, curr, prec) VALUES (2,'USD',2);
INSERT INTO curr (rn, curr, prec) VALUES (3,'EUR',2);
