-- Latvian COA
-- prepared by Kaspars Melkis <info@isolis.lv>
-- Sept. 14, 2003
-- checked and edited Sept. 20, 2003, D. Simader
--
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1','Ilgtermiņa ieguldījumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2','Apgrozāmie līdzekļi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('11','Nemateriālie ieguldījumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('12','Pamatlīdzekļi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1210','Zemes gabali, ēkas, būves, ilggadīgie stādījumi un citi nekustamā īpašuma objekti','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1290','Pamatlīdzekļu nolietojums (pasīvā)','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('13','Ilgtermiņa finansu ieguldījumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('21','Krājumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2130','Gatavās preces pārdošanai','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2310','Norēķini ar pircējiem un pasūtītājiem','A','L','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('23','Norēķini par prasībām (ar debitoriem)','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2350','Norēķini ar citiem debitoriem','A','A','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('26','Naudas līdzekļi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2610','Kase','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1380','Aizdevumi uzņēmuma dalībniekiem un valdei','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1310','Līdzdalība meitas uzņēmumu kapitālā','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1340','Aizdevumi saistītajiem uzņēmumiem','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1350','Pārējie vērtspapīri','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5','Kreditori','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1370','Pašu akcijas un daļas','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2210','Pieaugušie produktīvie lopi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3350','Statūtos paredzētās rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2220','Jaunlopi un sīkie dzīvnieki','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2320','Par piegādēm un pasūtījumiem saņemtie vekseļi','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2140','Nepabeigtie pasūtījumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2370','Īstermiņa aizdevumi sabiedrībām dalībniekiem un vadībai','A','A','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1360','Pārējie aizdevumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2120','Nepabeigtie ražojumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2330','Meitas uzņēmumu parādi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2340','Saistīto uzņēmumu parādi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2380','Norēķini par prasībām pret personālu un īstermiņa aizdevumi personālam','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2410','Nākamo periodu izdevumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2420','Akciju emisijas  nocenojums (disagio)','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('25','Vērtspapīri apgrozāmo līdzekļu sastāvā un īstermiņa līdzdalība kapitālos','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2510','Meitas  uzņēmuma akcijas un daļas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2520','Saistīto uzņēmuma akcijas un daļas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2530','Pašu  uzņēmuma akcijas un daļas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2540','Pārējie vērtspapīri un līdzdalība kapitālos','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2640','Akreditīvi, čeki un īpašu norēķina  formu konti','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2650','Citi konti bankās','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2670','Pārējie naudas līdzekļi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3','Pašu kapitāls','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3130','Ilgtermiņa ieguldījuma pārvērtēšanas rezerve','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3120','Akciju emisijas uzcenojums (agio)','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('32','Privātkonti','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3210','Privātiem nolūkiem izņemtie līdzekļi','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('33','Rezerves ','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3310','Rezerves kapitāls','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3330','Citas likumā paredzētās  rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3340','Rezerves pašu akcijām un daļām','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3360','Pārējās rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('34','Nesadalītā peļņa vai nesegtie zaudējumi','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3410','Pārskata gada nesadalītā peļņa','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3420','Iepriekšējo gadu nesadalītā peļņa','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4','Uzkrājumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4110','Uzkrājumi pensijām pielīdzinātām saistībām','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4310','Citi uzkrājumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('41','Uzkrājumi pensijām pielīdzināmātām saistībām','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('43','Citi uzkrājumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('42','Uzkrājumi paredzamiem nodokļiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('51','Norēķini par aizņēmumiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5110','Aizņēmumi pret obligācijām','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5120','Akcijās pārvēšamie aizņēmumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5130','Aizņēmumi ar līdzdalību peļņā','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5140','Citi aizņēmumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5150','Īstermiņa aizņēmumi  no kredītiestādēm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5160','Ilgtermiņa aizņēmumi no kredītiestādēm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5170','Aizņēmumi no kredītiestādēm bez norādītā termiņa','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52','Norēķini par saņemtajiem avansiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5210','Norēķini par saņemtiem avansiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('54','Maksājamie vekseļi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('53','Norēķini par piegādātājiem un darbuzņēmējiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5310','Norēķini par piegādātājiem un darbuzņēmējiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5410','Norēķini par pašu izdotajiem vekseļiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5510','Norēķini par parādiem meitas uzņēmumiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5540','Norēķini par parādiem citiem uzņēmumiem un dalībniekiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5550','Norēķini par parādiem personālam','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5520','Norēķini par parādiem saistītiem uzņēmumiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5530','Norēķini par parādiem uzņēmumiem, ar kuriem ir līgums par līdzdalību','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('57','Norēķini par nodokļiem','H','L','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('58','Norēķini par  dividendēm','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('61','Ieņēmumi no pārdošanas, kas apliekami ar nodokļiem vispārējā kārtībā','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('62','Ieņēmumi no pārdošanas, kas citādi  apliekami ar nodokļiem','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6220','Ar īpašiem nodokļiem apliekamie pārdošanas ieņēmumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('63','Komisijas, starpniecības un citi ieņēmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6310','Komisijas un starpniecības ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6320','Ieņēmumi no atkritumu pārstrādes un realizācijas','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6330','Ieņēmumi no taras realizācijas','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6340','Ar nodokļiem neapliekamie apgrozījumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('64','Ieņēmumus samazinošas atlaides','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6410','Piešķirtās skonto atlaides','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6420','Piešķirtie bonusi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('59','Nākamo periodu ieņēmumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('65','Pārējie uzņēmuma ieņēmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6510','Ieņēmumi no vērtspapīru kursa paaugstināšanās','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6530','Ieņēmumi no zemes gabalu iznomāšanas','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6540','Ieņēmumi no apgrozāmo līdzekļu pārdošanas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6550','Ieņēmumi no pamatlīdzekļu iznomāšanas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6560','Ieņēmumos pārskaitītais rezervju un uzkrājumu samazinājums','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6570','Iepriekšējo gadu nodokļu samazinājums','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6580','Papildus  ieguldījumi un citi ieņēmumi','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6590','Pašu uzņēmuma kapitālieguldījumiem izpildītie darbi','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('67','Citu periodu ieņēmumi, kas attiecas uz pārskata periodu','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6710','Citu periodu ieņēmumi, kas attiecas uz pārskata periodu','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('69','Sociālās infrastruktūras iestāžu un pasākumu ieņēmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6930','Sadzīves paklpojumu ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6920','Komunālās  saimniecības ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('66','Gatavās produkcijas  un nepabeigto  ražojumu krājumu un vērtības  izmaiņas','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6610','Gatavās produkcijas krājumu un vērtības izmaiņas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6620','Nepabeigto ražojumu krājumu un vērtības  izmaiņas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6630','Nepabeigto pasūtījumu atlikumu un vētības izmaiņas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6640','Produktīvo  un darba dzīvnieku ganāmpulka vērtības izmaiņas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6940','Sabiedriskās ēdināšanas ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6950','Izglītības iestāžu ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6960','Medicīnas iestāžu ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6970','Kultūras un sporta ietāžu un pasākumu ieņēmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6980','Pārējie sociālās infrastruktūras iestāžu un pasākumu ieņēmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7','Saimnieciskās darbības izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('71','Izdevumi izejvielu, materiālu un preču iepirkšanai','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7110','Izejvielu un materiālu iepirkšanas un piegādes izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7120','Preču iepirkšanas un piegādes izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7130','Saņemtās atlaides','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7140','Taras izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7150','Muitas un ievednodevas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7160','Pārējie ārējie izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7170','Samaksa par darbiem un pakalpojumiem no ārienes','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7190','Pirkto materiālu un preču krājumu un vērtības izmaiņas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('72','Personāla izmaksas','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7210','Strādnieku algas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7230','Sociālās  infrastruktūras  iestāžu un pasākumu darbinieku algas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('73','Sociālās nodevas un izmaksas','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7320','Pārējās sociālās izmaksas','A','E','AP_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('74','Pamatlīdzekļu nolietojums un citu ieguldījumu vērtības norakstījumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7410','Nemateriālo ieguldījumu vērtības norakstīšana','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('75','Pārējie saimnieciskās darbības  izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7510','Dabas aizsardzības izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7530','Nodevas par ražošanā izmantotiem zemes gabaliem','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7440','Apgrozāmo līdzekļu vērtības norakstīšana','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7540','Apdrošinnāšanas maksājumi (izņemot darbinieku apdrošināšanu)','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7550','Pārējie saimnieciskās darbības izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7560','Strādnieku vervēšanas un apmācības izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('76','Preču pārdošanas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7610','Iesaiņojamais materiāls, tara','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7620','Preču transporta izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7630','Preču transporta apdrošināšana','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7640','Samaksātās komisijas naudas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7650','Citi pārdošanas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('77','Administrācijas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7710','Sakaru izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7720','Kantora (biroja) izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7730','Juristu pakalpojumu apmaksa','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7740','Gada pārskata un revīzijas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7750','Naudas apgrozījuma blakus izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7760','Transporta izdevumi administrācijas vajadzībām','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7770','Citi vadīšanas un administrācijas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('78','Pārskata periodā iekļaujamie iepriekšējo periodu izdevumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7810','Pārskata periodā iekļaujamie iepriekšējo periodu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('79','Sociālās  infrastruktūras uzturēšanas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7920','Komuālās saimniecības izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7940','Sabiedriskās ēdināšanas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7950','Izglītības iestāžu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8','Dažādi ieņēmumi un izdevumi, peļņa un zaudējumi','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('81','Dažādi ieņēmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8110','Ieņēmumi no līdzdalības, vērtspapīriem un aizdevumiem','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8120','Pārējie ieņēmumi no procentiem un tiem pielīdzināmi ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7910','Dzīvokļu saimniecības izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8130','Vekseļu diskonta ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8150','Ienākumi no valūtas kursa paaugstināšanās','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8160','Saņemtās soda naudas un līgumsodi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8170','Peļņa no ārzemju valūtas pārdošanas vai pirkšanas','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8190','Citi ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('82','Dažādi izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8210','Īstermiņa finansu ieguldījumu vērtības norakstīšana','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8220','Samaksātie procenti un tiem pielīdzināmie izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8230','Vekseļu diskonta izmaksas','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8240','Ilgtermiņa aizdevumu procentu samaksa','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8260','Samaksātās soda naudas un līgumsodi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8270','Zaudējumi no ārzemju valūtas pirkšanas un pārdošanas','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8290','Citi izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('83','Ārkārtas ieņēmumi','H','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8310','Ārkārtas ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('84','Ārkārtas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8410','Ārkārtas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('86','Peļņa vai zaudējumi','H','I','IC_income:IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8610','Peļņa vai zaudējumi','A','I','IC_income:IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3220','Privātie ieguldījumi','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6110','Ieņēmumi no pamatdarbības  produkcijas un pakalpojumu pārdošanas','A','I','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1220','Tehnoloģiskās  iekārtas un mašīnas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1240','Pamatlīdzekļu izveidošana un nepabeigto celtniecības objektu izmaksas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1320','Aizdevumi meitas uzņēmumam','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2110','Izejvielas un materiāli','A','A','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2190','Avansa maksājumi par precēm','A','A','AR','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1130','Uzņēmuma nemateriālā vērtība','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1180','Avansa maksājumi par nemateriāliem aktīviem','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1190','Nemateriālo ieguldījumu vērtības norakstītā daļa (pasīvā)','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('22','Produktīvie un darba dzīvnieki','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2230','Darba lopi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2290','Darba lopu norakstītā vērtība (pasīvā)','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2360','Norēķini par parakstītā sabiedrības kapitālā neiemaksātām summām','A','A','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('24','Nākamo periodu izdevumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2620','Norēķinu konti bankā','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3110','Pamatkapitāls vai līdzdalības kapitāls','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('55','Norēķini ar uzņēmumiem, dalībniekiem un personālu','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('56','Norēķini  par darba samaksu  un ieturējumiem (izņemot nodokļus)','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5610','Norēķini par darba algu','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5620','Norēķini par ieturējumiem no darba algas (izņemot nodokļus)','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5820','Norēķini par iepriekšējo gadu neizmaksātajām dividendēm','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5810','Norēķini par pārskata gada dividendēm','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5910','Nākamo periodu ieņēmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6','Ieņēmumi no uzņēmuma saimnieciskās darbības','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6210','Ar nodokļiem neapliekamie pārdošanas ieņēmumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6430','Piešķirtie rabati un citas tirdzniecības  atlaides','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6910','Dzīvokļu saimniecības ieņēmumi','A','I','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7180','Pārējie materiālie izdevumi (nodoklis par dabas resursu izmantošanu, celmu nauda u.c.)','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7240','Pārējās personāla izmaksas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7220','Pārvaldes personāla un administratīvā personāla algas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7420','Pamatlīdzekļu nolietojums','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7570','Komandējuma izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7930','Sadzīves pakalpojumu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7960','Medicīniskās apkalpošanas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7970','Kultūras un sporta iestāžu un pasākumu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8140','Ziedojumi un citi tiem pielīdzināmi ieņēmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8250','Zaudējumi no valūtu  kursa pazemināšanās','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7980','Pārējie sociālās infrastruktūras uzturēšanas izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('87','Peļņas izlietojums (bez nodokļiem)','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('88','Nodoļi no peļņas un citi saimnieciskās darbības izdevumos neiekļaujamie nodokļi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1110','Pētniecības un uzņēmuma attīstības izmaksas','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1120','Koncesijas, patenti, licences, tirdzniecības zīmes un līdzīgas tiesības; datoru programmas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1230','Pārējie pamatlīdzekļi un inventārs','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5710','Norēķini par peļņas nodokli','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2390','Pārmaksātie nodokļi, iepriekš samaksātie nodokļi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4210','Uzkrājumi paredzamiem nodokļiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5720','Norēķini par citiem nodokļiem, nodevām un maksājumiem budžetam','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7310','Sociālais nodoklis','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8710','Peļņas izlietojums','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8830','Nodoklis par zemi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8840','Citi saimnieciskās darbības izmaksās neiekļaujamie nodokļi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8820','Nodoklis par dabas resursu izmantošanu no peļņas  maksājamā daļā','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8810','Nodoklis no peļņas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1330','Līdzdalības saistīto uzņēmumu kapitālā','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2354','PVN samaksāts 18%','A','E','AP_tax:IC_taxpart:IC_taxservice','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2352','PVN ieņemtais 18%','A','L','AR_tax:IC_taxpart:IC_taxservice','');
--
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2352'),'0.18','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2354'),'0.18','');
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1230'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '6010'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '7110'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '8170'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '8270'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, prec) VALUES (1,'LVL',2);
INSERT INTO curr (rn, curr, prec) VALUES (2,'EUR',2);
INSERT INTO curr (rn, curr, prec) VALUES (3,'USD',2);

