-- Chart of Account for Poland
-- From: Peter Dabrowski <meritage@mail.com>
-- Sun, 23 March 2003
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('000000000','Aktywa Trwałe','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001000000','Środki Trwałe','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001010000','Grunty własne i prawa wieczystego użytkowania gruntów','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001020000','Budynki, locale i obiekty inżynierii lądowej i wodnej','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001030000','Urządzenia techniczne i maszyny','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001040000','Środki transportu','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('001050000','Inne środki trwałe','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('002000000','Wartości niematerialne i prawne','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('002010000','Koszty zakończonych prac rozwojowych','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('002020000','Nabyta wartość firmy','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('002080000','Inne wartości niematerialne i prawne','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('002090000','Zaliczki na wartości niematerialne i prawne','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003000000','Długoterminowe aktywa finansowe','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003010000','W jednostkach powiązanych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003010100','Udziały lub akcje','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003010200','Inne papiery wartościowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003010300','Udzielone porzyczki','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003010400','Inne długoterminowe aktywa finansowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003020000','W pozostałych jednostkach','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003020100','Udziały lub akcje','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003020200','Inne papiery wartościowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003020300','Udzielone pożyczki','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003020400','Inne długoterminowe aktywa finansowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003090000','Inne investycje długoterminowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('003090100','Inne rodzaje długoterminowych aktywów finansowych','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('004000000','Investycje w nieruchomości i prawa','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('004010000','Nieruchomości','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('004020000','Wartości niematerialne i prawne','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('005000000','Długoterminowe rozliczenia międzyokresowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('005010000','Aktywa z tytułu odroczonego podatku dochodowego','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('005020000','Inne rozliczenia międzyokresowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('006000000','Należności długoterminowe','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('006010000','Od jednostek powiązanych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('006020000','Od pozostałych jednostek','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007000000','Odpisy umorzeniowe środków trwałych oraz wartości niematerialnych i prawnych','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007010000','Odpisy umorzeniowe wartości gruntów i prawa wieczystego użytkowania gruntów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007020000','Odpisy umorzeniowe budynków, lokali i obiektów inżynierii lądowej i wodnej','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007030000','Odpisy umorzeniowe urządzeń technicznych i maszyn','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007040000','Odpisy umorzeniowe środków transportu','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007050000','Odpisy umorzeniowe ulepszeń obcych środków trwałych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('007090000','Odpisy umorzeniowe innych środków trwałych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008000000','Środki trwałe w budowie','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008010000','Inwestycje budowy środka trwałego','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008020000','Ulepszenia środka trwałego','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008030000','Nakłady na budowę środka trwałego','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008040000','Zaliczki na środki trwałe w budowie','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('008050000','Ulepszenia obcych środków trwałych','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('009000000','Odpisy aktualizujące długoterminowe aktywa finansowe','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('009010000','Odpisy aktualizujące udziały i akcje w obcych jednostkach','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('009020000','Odpisy aktualizujące lokaty','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('009030000','Odpisy aktualizujące udzielone porzyczki długoterminowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('009090000','Odpisy aktualizujące inne rodzaje długoterminowych aktywów finansowych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('100000000','Środki pieniężne, rachunki bankowe oraz inne krótkoterminowe aktywa finansowe','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('110000000','Środki pieniężne w kasie','A','','A','AR:AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('110010000','Kasa krajowych środków pieniężnych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('110020000','Kasa EUR zagranicznych środków pieniężnych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('110030000','Kasa USD zagranicznych środków pieniężnych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113000000','Rachunki i kredyty bankowe','A','','A','AR:AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113010000','Rachunek bieżący','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113020000','Rachunek środków wyodrębnionych i zablokowanych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113030000','Rachunki kredytów bankowych','A','','A','AR_paid:AP_amount:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113040000','Rachunek EUR środków walutowych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('113050000','Rachunek USD środków walutowych','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114000000','Krótkoterminowe aktywa finansowe','A','','A','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114010000','Krótkoterminowe aktywa finansowe w jednostkach powiązanych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114010100','Udziały lub akcje','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114010200','Inne papiery wartościowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114010300','Udzielone pożyczki','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114010400','Inne krótkoterminowe aktywa finansowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114020000','Krótkoterminowe aktywa finansowe w pozostałych jednostkach','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114020100','Udziały lub akcje','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114020200','Inne papiery wartościowe','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('114020400','Inne krótkoterminowe aktywa finansowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('115000000','Inne środki pieniężne','A','','A','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('116000000','Inne aktywa pieniężne','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('117000000','Inne inwestycje krótkoterminowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('118000000','Krótkoterminowe rozliczenia międzyokresowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('200000000','Rozrachunki i roszczenia','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220000000','Należności krótkoterminowe','A','','L','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010000','Należności od jednostek powiązanych','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010100','Należności z tytułu dostaw i usług','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010110','Należności z tytułu dostaw i usług, o okresie spłaty do 12 miesięcy','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010120','Należności z tytułu dostaw i usług, o okresie spłaty powyżej 12 miesięcy','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010200','Inne należności','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010210','Zobowiązania z tytułu pokrycia kosztów ogólnego zarządu','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('220010220','Zobowiązania z tytułu rozliczeń VAT','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221010000','Należności od pozostałych jednostek','A','','L','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020100','Należności z tytułu dostaw i usług','A','','L','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020110','Należności z tytułu dostaw i usług, o okresie spłaty do 12 miesięcy','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020120','Należności z tytułu dostaw i usług, o okresie spłaty powyżej 12 miesięcy','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020200','Należności z tytułu podatków, dotacji, ceł, ubezpieczeń społecznych i zdrowotnych oraz innych świadczeń','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020300','Zaliczki przekazane dostawcom','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020400','Należności dochodzone na drodze sądowej','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('221020500','Inne należności','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222000000','Zobowiązania krótkoterminowe','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222010000','Zobowiązania wobec jednostek powiazanych','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222010100','Zobowiązania z tytułu dostaw i usług','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222010200','Zobowiązania o okresie wymagalności do 12 miesięcy','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222010300','Zobowiązania o okresie wymagalności powyżej 12 miesięcy','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222010400','Inne zobowiązania','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020000','Zobowiązania wobec pozostałych jednostek','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020100','Kredyty i pożyczki','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020200','Zobowiązania z tytułu emisji dłużnych papierów wartościowych','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020300','Inne zobowiązania finasowe','A','','L','AP_Amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020400','Zobowiazania z tytułu dostaw i usług','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020500','Zobowiązania o okresie wymagalności do 12 miesięcy ','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020600','Zobowiązania o okresie wymagalności powyżej 12 miesięy','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020700','Zaliczki otrzmane na dostawy','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020800','Zobowiązania wekslowe','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222020900','Zobowiązania z tytułu podatków, ceł, ubezpieczeń i innych świadczeń','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222021000','Zobowiązania z tytułu wynagrodzeń','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('222021100','Inne zobowiązania','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223000000','Rozrachunki publicznoprawne','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223010000','Rozrachunki z urzędem skarbowym z tytułu VAT','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223020000','Rozliczenie należnego VAT','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223020100','Rozliczenie należnego VAT-23%','A','','L','AR_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223020200','Rozliczenie należnego VAT-8%','A','','L','AR_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223020300','Rozliczenie należnego VAT-0%','A','','L','AR_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223030000','Rozliczenie naliczonego VAT','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223030100','Rozliczenie naliczonego VAT-23%','A','','L','AP_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223030200','Rozliczenie naliczonego VAT-8%','A','','L','AP_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223030300','Rozliczenie naliczonego VAT-0%','A','','L','AP_tax:IC_taxpart:IC_taxservice');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223040000','Korekty naliczonego VAT','A','','L','AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223050000','Rozrachunki z Urzędem Celnym','A','','L','AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223060000','Rozrachunki z Urzędem Skarbowym z tytułu znaków akcyzy','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223070000','Rozrachunki z Urzędem Skarbowym z tytułu podatku akcyzowego','A','','L','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223080000','Rozliczenie znaków akcyzy','A','','L','AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223090000','Rozrachunki z ZUS','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('223100000','Rozrachunki z Urzędem Skarbowym z tytułu podatku dochodowego od osób prawnych','A','','L','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('224000000','Rozrachunki z pracownikami','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('224010000','Rozrachunki z tytułu wynagrodzeń','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('224020000','Rozrachunki z tytułu pożyczek udzielonych pracownikom','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('224090000','Inne rozrachunki z pracownikami','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225000000','Zobowiązania długoterminowe','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225010000','Zobowiązania wobec jednostek powiązanych','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225010100','Zobowiązania z tytułu wyodrębnienia składników majątkowych','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225010200','Zobowiązania z tytułu podziału zysku','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020000','Zobowiązania wobec pozostałych jednostek','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020100','Kredyty i pożyczki otrzymane','A','','L','AR_amount:AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020200','Kredyty i pożyczki udzielone','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020300','Zobowiązania z tytułu emisji dłużnych papierów wartościowych','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020400','Inne zobowiązania kredytowe','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225020500','Inne zobowiązania','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225030000','Rozrachunki z tytułu wpłat na kapitał zakładowy','A','','L','AR_amount:APamount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225040000','Rozrachunki z tytułu wkładów niepieniężnych na kapitał zakładowy','A','','L','AR_amount:AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225050000','Rozrachunki z tytułu podwyższenia kapitału ze środków własnych spółki','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225060000','Rozrachunki z tytułu umorzenia udziałów własnych','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225070000','Rozrachunki z tytułu dywident','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225080000','Rozrachunki z tytułu dopłat i zwrotu dopłat','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('225090000','Pozostałe rozrachunki ze wspólnikami','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('229000000','Odpisy aktualizujące rozrachunki','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('300000000','Materiały i towary','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330000000','Rozliczenie zakupu','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330010000','Rozliczenie wartości materiałów i towarów w drodze','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330020000','Wartości dostaw niefakturowanych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330030000','Przychody wszelkich dostaw i usług i ich rozliczanie','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330040000','Odhylenia cen ewidencyjnych od rzeczywistych cen nabycia lub zakupu','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330050000','Koszty zakupu zawarte w fakturach dostawców','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330060000','Opłaty manipulacyjne policzone przez Urząd Celny','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330070000','Niedobory, szkody i nadwyżki w transporcie','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330080000','Znaki akcyzy według dokumentu SAD','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('330090000','Reklamacje faktur dostawców','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('331000000','Materiały','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('331010000','Materiały w magazynach własnych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('331020000','Materiały w magazynach obcych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('331030000','Materiały w przerobie','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('333000000','Towary','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('333010000','Towary w magazynach własnych','A','','A','IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('333020000','Towary w magazynach obcych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('333030000','Towary w detalu','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('334000000','Odchylenia od cen ewidencyjnych materiałów i towarów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('334010000','Odpisy aktualizujące wartość materiałów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('334020000','Odpisy aktualizujące wartość towarów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('400000000','Koszty według rodzajów i ich rozliczeń','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440000000','Koszty według rodzajów','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440010000','Zużycie materiałów i energii','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440010100','Zużycie materiałów biurowych','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020000','Usługi obce','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020100','Usługi celne','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020200','Usługi telekomunikacyjne','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020300','Usługi pocztowe','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020400','Usługi kurierskie i transportowe','A','','E','AP_amount:IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020500','Analizy sanitarne','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440020600','Usługi graficzne i drukarskie','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440030000','Podatki i opłaty','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440030100','Opłaty i prowizje bankowe','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440030200','Opłaty sądowe, prawnicze i notarialne','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440030300','Opłaty skarbowe','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440030400','Koncesje','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('440040000','Wynagrodzenia za pracę','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('441000000','Świadczenia na rzecz pracowników','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('442000000','Amortyzacja','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('443000000','Pozostałe','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('449000000','Rozliczenie kosztów','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('449010000','Nie podlegające rozliczeniu w czasie','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('449020000','Przypadające na przyszłe okresy','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('449030000','Koszty zgromadzone','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('449040000','Koszty nie wliczane do wartości sprzedaży','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('500000000','Koszty według typów działalności i ich rozliczenie','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('550000000','Koszty działalności podstawowej-produkcyjnej','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('550010000','Rozliczone koszta działalności','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('550020000','Koszty nie zakończonych długotrwałych usług','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('550030000','Straty związane z wykonaniem długotrwałych usług','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('552000000','Koszty działalności podstawowej-handlowej','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('552010000','Koszty utrzymania punktów sprzedaźy detalicznej','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('550200000','Koszty utrzymania hurtowni','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('552030000','Koszty sprzedaży wyrobów','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('552040000','Podatek akcyzowy','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('552050000','Opłaty celne','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('553000000','Koszty działalności pomocniczej','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('553010000','Świadczenia usług transportowych','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('555000000','Koszty zarządu','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('555010000','Koszty zarządzania jednostką','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('555020000','Świadczenia usług na potrzeby reprezentacji i reklamy','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('558000000','Rozliczenie kosztów działalności','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('600000000','Produkty i rozliczenia międzyokresowe','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('660000000','Półprodukty i produkty w toku','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('661000000','Produkty gotowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('661010000','Wyroby gotowe','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('661020000','Wyroby poza jednostką','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('662000000','Odchylenia od cen ewidencyjnych produktów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('662010000','Odchylenia od cen evidencyjnych wyrobów gotowych','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('662020000','Odhylenia od cen evidencyjnych półfabrykatów','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('664000000','Rozliczenia międzyokresowe kosztów','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('664010000','Czynne rozliczenia międzyokresowe kosztów','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('664020000','Bierne rozliczenia międzyokresowe kosztów','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('665000000','Pozostałe rozliczenia międzyokresowe','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('665010000','Czynne rozliczenia przyszłych okresów','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('665020000','Bierne rozliczenia przyszłych okresów','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('700000000','Przychody i koszty związane z ich osiągnięciem','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770000000','Sprzedaż produktów','A','','I','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770010000','Sprzedaż produktów na kraj','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770020000','Sprzedaż produktów na eksport','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770030000','Sprzedaż usług na kraj','A','','I','AR_amount:IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770040000','Sprzedaż usług na eksport','A','','I','AR_amount:IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770100000','Koszty sprzedanych produktów','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770110000','Koszt własny sprzedaży produktów na kraj','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770120000','Koszt własny sprzedaży produktów na eksport','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770130000','Koszt własny sprzedaży usług na kraj','A','','E','IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('770140000','Koszt własny sprzedaży usług na export','A','','E','IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773000000','Sprzedaż towarów','A','','I','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773010000','Sprzedaż hurtowa towarów','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773020000','Sprzedaż detaliczna towarów','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773030000','Sprzedaż wysyłkowa towarów','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773040000','Prowizja komisowa','A','','I','AR_amount:IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773100000','Wartość sprzedanych towarów w cenach zakupu','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773110000','Wartość sprzedanych towarów w sprzedaży hurtowej','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773120000','Wartość sprzedanych towarów w sprzedaży detalicznej','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773130000','Wartość sprzedanych towarów w sprzedaży wysyłkowej','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('773140000','Prowizja komisowa','A','','E','AP_amount:IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774000000','Sprzedaż materiałów','A','','I','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774010000','Materiały','A','','I','AP_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774020000','Opakowania','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774030000','Odpady','A','','I','AR_amount:IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774100000','Wartość sprzedanych materiałów','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774110000','Wartość w cenach zakupu sprzedanych materiałów','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774120000','Wartość w cenach zakupu sprzedanych opakowań','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('774130000','Wartość w cenach zakupu sprzedanych odpadów','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775000000','Przychody finansowe','A','','I','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775010000','Kwoty należne ze sprzedaży aktywów finansowych','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775020000','Kwoty należne z tytułu dywident','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775030000','Otrzymane odsetki','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775040000','Przychody ze zbycia investycji','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775050000','Aktualizacja wartości investycji-przychody','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775060000','Dodatnie różnice kursu walut','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775070000','Pozostałe przychody finansowe','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775100000','Koszty finansowe','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775110000','Wartość sprzedanych investycji','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775120000','Odpisy z tytułu utraty wartości investycji-koszty','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775130000','Odsetki zapłacone','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775140000','Ujemne różnice kursu walut','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('775190000','Pozostałe koszty finansowe','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776000000','Pozostałe przychody operacyjne','A','','I','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776010000','Przychody ze zbycia niefinansowych aktywów trwałych','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776020000','Otrzymane dotacje','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776030000','Przychody z usług socjalnych','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776040000','Przychody ze wzrostu wartości niefinansowych aktywów trwałych','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776090000','Inne pozostałe przychody operacyjne','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776100000','Pozostałe koszty operacyjne','A','','E','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776110000','Wartość sprzedanych niefinansowych aktywów trwałych','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776120000','Dotacje przekazane','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776130000','Odpisy z tytułu utraty wartości aktywów niefinansowych','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('776140000','Inne pozostałe koszty operacyjne','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('777000000','Zyski nadzwyczajne','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('777100000','Straty nadzwyczajne','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779000000','Obroty wewnętrzne','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779010000','Koszt wyrobów własnej produkcji wydanych do własnych sklepów','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779020000','Świadczenia na rzecz środków trwałych w budowie','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779040000','Koszt niedoborów produktów','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779050000','Koszt zaniechania określonego rodzaju działalności','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779100000','Koszt obrotów wewnętrznych','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779110000','Koszt wytworzenia wyrobów gotowych wydanych do własnych sklepów','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779120000','Koszt wytworzenia świadczeń na rzecz środków trwałych w budowie','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779130000','Koszt wytworzenia zakończonych prac rozwojowych','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779140000','Koszt wytworzenia produktów uznanych za niedobory','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('779150000','Koszt zaniechania określonego rodzaju działalności','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('800000000','Kapitały własne i wynik finansowy','H','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('880000000','Kapitał podstawowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('880010000','Kapitał zakładowy','A','','Q','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('881000000','Fundusze wydzielone jednostkom zależnym','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('882000000','Należne wpłaty na kapitał podstawowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('883000000','Fundusze wydzielone jednostkom zależnym','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('884000000','Kapitał zapasowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('885000000','Kapitał rezerwowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('886000000','Kapitał z aktualizacji wyceny','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('887000000','Rozliczenia wyniku finansowego','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('888000000','Rezerwy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('888010000','Rezerwa z tytułu odroczonego podatku dochodowego','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('888020000','Rezerwa na świadczenia','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('888020100','Rezerwa długoterminowa na świadczenia emerytalne i podobne','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('888020200','Rezerwa krótkoterminowa na świadczenia emerytalne i podobne','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('889090000','Pozostałe rezerwy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('889090100','Pozostałe rezerwy długoterminowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('889090200','Pozostałe rezerwy krótkoterminowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('890000000','Rozliczenia międzyokresowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('890010000','Ujemna wartość firmy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('890020000','Inne rozliczenia międzyokresowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('890020100','Inne rozliczenia międzyokresowe długoterminowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('890020200','Inne rozliczenia międzyokresowe krótkoterminowe','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('891000000','Fundusze specjalne','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('892000000','Wynik finansowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('893000000','Odpisy z zysku netto w ciągu roku obrotowego','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('893010000','Podatek dochodowy','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('893020000','Inne obowiązkowe obciążenia wyniku finansowego','A','','Q','');
--
insert into tax (chart_id,rate) values ((select id from chart where accno = '223020100'),0.23);
insert into tax (chart_id,rate) values ((select id from chart where accno = '223020200'),0.08);
insert into tax (chart_id,rate) values ((select id from chart where accno = '223020300'),0);
insert into tax (chart_id,rate) values ((select id from chart where accno = '223030100'),0.23);
insert into tax (chart_id,rate) values ((select id from chart where accno = '223030200'),0.08);
insert into tax (chart_id,rate) values ((select id from chart where accno = '223030300'),0);
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '333000000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '773010000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '773110000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '775060000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '775140000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, prec) VALUES (1,'PLN',2);
INSERT INTO curr (rn, curr, prec) VALUES (2,'USD',2);
INSERT INTO curr (rn, curr, prec) VALUES (3,'EUR',2);

