-- Slovak chart of accounts
-- Peter Meszaros <peterm@insypo.sk>
--
INSERT INTO gifi (accno,description) VALUES ('01','NEHMOTNÝ INVESTIČNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('02','HMOTNÝ INVESTIČNÝ MAJETOK ODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('03','HMOTNÝ INVEST. MAJETOK NEODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('04','OBSTARANIE NEHMOTNÝCH A HM. INVESTÍCIÍ');
INSERT INTO gifi (accno,description) VALUES ('05','POSKYTNUTÉ PREDDAVKY NA NEHM. IM A HIM');
INSERT INTO gifi (accno,description) VALUES ('06','FINANČNÉ INVESTÍCIE');
INSERT INTO gifi (accno,description) VALUES ('07','OPRÁVKY K NEHMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('08','OPRÁVKY K HMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('09','OPRAVNÉ POLOŽKY K IM');
INSERT INTO gifi (accno,description) VALUES ('11','MATERIÁL');
INSERT INTO gifi (accno,description) VALUES ('12','ZÁSOBY VLASTNEJ VÝROBY');
INSERT INTO gifi (accno,description) VALUES ('13','TOVAR');
INSERT INTO gifi (accno,description) VALUES ('19','OPRAVNÉ POLOŽKY');
INSERT INTO gifi (accno,description) VALUES ('21','PENIAZE');
INSERT INTO gifi (accno,description) VALUES ('22','ÚČTY V BANKÁCH');
INSERT INTO gifi (accno,description) VALUES ('23','BEŽNÉ BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('24','INÉ KRÁTKODOBÉ FINANČNÉ VÝPOMOCI');
INSERT INTO gifi (accno,description) VALUES ('25','KRÁTKODOBÝ FINANČNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('26','PREVODY MEDZI FINANČNÝMI ÚČTAMI');
INSERT INTO gifi (accno,description) VALUES ('29','OPRAVNÉ POLOŽKY KU KRÁTKOD. FIN. MAJETKU');
INSERT INTO gifi (accno,description) VALUES ('31','POHĽADÁVKY');
INSERT INTO gifi (accno,description) VALUES ('32','ZÁVÄZKY ');
INSERT INTO gifi (accno,description) VALUES ('33','ZÚČTOVANIE SO ZAMESTNANCAMI A INŠTITÚCIAMI');
INSERT INTO gifi (accno,description) VALUES ('34','ZÚČTOVANIE DANÍ A DOTÁCIÍ');
INSERT INTO gifi (accno,description) VALUES ('35','POHĽADÁVKY VOČI SPOLOČNÍKOM A ZDRUŽENIU');
INSERT INTO gifi (accno,description) VALUES ('36','ZÁVÄZKY VOČI SPOLOČNÍKOM A ZDRUŽENIU');
INSERT INTO gifi (accno,description) VALUES ('37','INÉ POHĽADÁVKY A ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('38','PRECHODNÉ ÚČTY AKTÍV A PASÍV');
INSERT INTO gifi (accno,description) VALUES ('39','OPR.POL. K ZÚČT. VZŤAHOM A VNÚTORNÉ ZÚČTOV.');
INSERT INTO gifi (accno,description) VALUES ('41','ZÁKLADNÉ IMANIE A KAPITÁLOVÉ FONDY');
INSERT INTO gifi (accno,description) VALUES ('42','FONDY ZO ZISKU A PREVEDENÉ HOSP. VÝSLEDKY');
INSERT INTO gifi (accno,description) VALUES ('43','HOSPODÁRSKY VÝSLEDOK');
INSERT INTO gifi (accno,description) VALUES ('45','REZERVY');
INSERT INTO gifi (accno,description) VALUES ('46','BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('47','DLHODOBÉ ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('48','ODLOŽENÁ DAŇ');
INSERT INTO gifi (accno,description) VALUES ('49','INDIVIDUÁLNY PODNIKATEĽ');
INSERT INTO gifi (accno,description) VALUES ('50','SPOTREBOVANÉ NÁKUPY');
INSERT INTO gifi (accno,description) VALUES ('51','SLUŽBY');
INSERT INTO gifi (accno,description) VALUES ('52','OSOBNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('53','DANE A POPLATKY');
INSERT INTO gifi (accno,description) VALUES ('54','INÉ PREVÁDZKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('55','ODPISY,REZERVY A OPR. POL. PREVÁDZKOVÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('56','FINANČNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('57','REZERVY A OPRAVNÉ POLOŽKY FINANČNÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('58','MIMORIADNE NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('59','DANE Z PRÍJMOV A PREVODOVÉ ÚČTY');
INSERT INTO gifi (accno,description) VALUES ('60','TRŽBY ZA VLASTNÉ VÝKONY A TOVAR');
INSERT INTO gifi (accno,description) VALUES ('61','ZMENA STAVU VNÚTROPODNIKOVÝCH ZÁSOB');
INSERT INTO gifi (accno,description) VALUES ('62','AKTIVÁCIA');
INSERT INTO gifi (accno,description) VALUES ('64','INÉ PREVÁDZKOVÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('65','ZÚČT. REZERV A OPR. POLOŽIEK PREVÁDZKOV. V.');
INSERT INTO gifi (accno,description) VALUES ('66','FINANČNÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('67','ZÚČT. REZERV A OPRAVNÝCH POL. FINANČNÝCH V.');
INSERT INTO gifi (accno,description) VALUES ('68','MIMORIADNE VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('69','PREVODOVÉ ÚČTY');
INSERT INTO gifi (accno,description) VALUES ('70','ZAČIATOČNÝ A KONEČNÝ ÚČET');
INSERT INTO gifi (accno,description) VALUES ('71','ÚČET ZISKOV A STRÁT');
INSERT INTO gifi (accno,description) VALUES ('80','VNÚTROPODNIKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('90','VNÚTROPODNIKOVÉ VÝNOSY');
--