-- Slovak chart of accounts UTF-8
-- Peter Meszaros <peterm@insypo.sk>
--
SET client_encoding = 'UTF-8';
--
INSERT INTO gifi (accno,description) VALUES ('01','NEHMOTNÝ INVESTIČNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('02','HMOTNÝ INVESTIČNÝ MAJETOK ODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('03','HMOTNÝ INVEST. MAJETOK NEODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('04','OBSTARANIE NEHMOTNÝCH A HM. INVESTÍCIÍ');
INSERT INTO gifi (accno,description) VALUES ('05','POSKYTNUTÉ PREDDAVKY NA NEHM. IM A HIM');
INSERT INTO gifi (accno,description) VALUES ('06','FINANČNÉ INVESTÍCIE');
INSERT INTO gifi (accno,description) VALUES ('07','OPRÁVKY K NEHMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('08','OPRÁVKY K HMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('09','OPRAVNÉ POLOŽKY K IM');
INSERT INTO gifi (accno,description) VALUES ('11','MATERIÁL');
INSERT INTO gifi (accno,description) VALUES ('12','ZÁSOBY VLASTNEJ VÝROBY');
INSERT INTO gifi (accno,description) VALUES ('13','TOVAR');
INSERT INTO gifi (accno,description) VALUES ('19','OPRAVNÉ POLOŽKY');
INSERT INTO gifi (accno,description) VALUES ('21','PENIAZE');
INSERT INTO gifi (accno,description) VALUES ('22','ÚČTY V BANKÁCH');
INSERT INTO gifi (accno,description) VALUES ('23','BEŽNÉ BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('24','INÉ KRÁTKODOBÉ FINANČNÉ VÝPOMOCI');
INSERT INTO gifi (accno,description) VALUES ('25','KRÁTKODOBÝ FINANČNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('26','PREVODY MEDZI FINANČNÝMI ÚČTAMI');
INSERT INTO gifi (accno,description) VALUES ('29','OPRAVNÉ POLOŽKY KU KRÁTKOD. FIN. MAJETKU');
INSERT INTO gifi (accno,description) VALUES ('31','POHĽADÁVKY');
INSERT INTO gifi (accno,description) VALUES ('32','ZÁVÄZKY ');
INSERT INTO gifi (accno,description) VALUES ('33','ZÚČTOVANIE SO ZAMESTNANCAMI A INŠTITÚCIAMI');
INSERT INTO gifi (accno,description) VALUES ('34','ZÚČTOVANIE DANÍ A DOTÁCIÍ');
INSERT INTO gifi (accno,description) VALUES ('35','POHĽADÁVKY VOČI SPOLOČNÍKOM A ZDRUŽENIU');
INSERT INTO gifi (accno,description) VALUES ('36','ZÁVÄZKY VOČI SPOLOČNÍKOM A ZDRUŽENIU');
INSERT INTO gifi (accno,description) VALUES ('37','INÉ POHĽADÁVKY A ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('38','PRECHODNÉ ÚČTY AKTÍV A PASÍV');
INSERT INTO gifi (accno,description) VALUES ('39','OPR.POL. K ZÚČT. VZŤAHOM A VNÚTORNÉ ZÚČTOV.');
INSERT INTO gifi (accno,description) VALUES ('41','ZÁKLADNÉ IMANIE A KAPITÁLOVÉ FONDY');
INSERT INTO gifi (accno,description) VALUES ('42','FONDY ZO ZISKU A PREVEDENÉ HOSP. VÝSLEDKY');
INSERT INTO gifi (accno,description) VALUES ('43','HOSPODÁRSKY VÝSLEDOK');
INSERT INTO gifi (accno,description) VALUES ('45','REZERVY');
INSERT INTO gifi (accno,description) VALUES ('46','BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('47','DLHODOBÉ ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('48','ODLOŽENÁ DAŇ');
INSERT INTO gifi (accno,description) VALUES ('49','INDIVIDUÁLNY PODNIKATEĽ');
INSERT INTO gifi (accno,description) VALUES ('50','SPOTREBOVANÉ NÁKUPY');
INSERT INTO gifi (accno,description) VALUES ('51','SLUŽBY');
INSERT INTO gifi (accno,description) VALUES ('52','OSOBNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('53','DANE A POPLATKY');
INSERT INTO gifi (accno,description) VALUES ('54','INÉ PREVÁDZKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('55','ODPISY,REZERVY A OPR. POL. PREVÁDZKOVÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('56','FINANČNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('57','REZERVY A OPRAVNÉ POLOŽKY FINANČNÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('58','MIMORIADNE NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('59','DANE Z PRÍJMOV A PREVODOVÉ ÚČTY');
INSERT INTO gifi (accno,description) VALUES ('60','TRŽBY ZA VLASTNÉ VÝKONY A TOVAR');
INSERT INTO gifi (accno,description) VALUES ('61','ZMENA STAVU VNÚTROPODNIKOVÝCH ZÁSOB');
INSERT INTO gifi (accno,description) VALUES ('62','AKTIVÁCIA');
INSERT INTO gifi (accno,description) VALUES ('64','INÉ PREVÁDZKOVÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('65','ZÚČT. REZERV A OPR. POLOŽIEK PREVÁDZKOV. V.');
INSERT INTO gifi (accno,description) VALUES ('66','FINANČNÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('67','ZÚČT. REZERV A OPRAVNÝCH POL. FINANČNÝCH V.');
INSERT INTO gifi (accno,description) VALUES ('68','MIMORIADNE VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('69','PREVODOVÉ ÚČTY');
INSERT INTO gifi (accno,description) VALUES ('70','ZAČIATOČNÝ A KONEČNÝ ÚČET');
INSERT INTO gifi (accno,description) VALUES ('71','ÚČET ZISKOV A STRÁT');
INSERT INTO gifi (accno,description) VALUES ('80','VNÚTROPODNIKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('90','VNÚTROPODNIKOVÉ VÝNOSY');
=======
-- Slovak chart of accounts
-- Peter Meszaros <peterm@insypo.sk>
--
INSERT INTO gifi (accno,description) VALUES ('01','NEHMOTN� INVESTI�N� MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('02','HMOTN� INVESTI�N� MAJETOK ODPISOVAN�');
INSERT INTO gifi (accno,description) VALUES ('03','HMOTN� INVEST. MAJETOK NEODPISOVAN�');
INSERT INTO gifi (accno,description) VALUES ('04','OBSTARANIE NEHMOTN�CH A HM. INVEST�CI�');
INSERT INTO gifi (accno,description) VALUES ('05','POSKYTNUT� PREDDAVKY NA NEHM. IM A HIM');
INSERT INTO gifi (accno,description) VALUES ('06','FINAN�N� INVEST�CIE');
INSERT INTO gifi (accno,description) VALUES ('07','OPR�VKY K NEHMOTN�MU IM');
INSERT INTO gifi (accno,description) VALUES ('08','OPR�VKY K HMOTN�MU IM');
INSERT INTO gifi (accno,description) VALUES ('09','OPRAVN� POLO�KY K IM');
INSERT INTO gifi (accno,description) VALUES ('11','MATERI�L');
INSERT INTO gifi (accno,description) VALUES ('12','Z�SOBY VLASTNEJ V�ROBY');
INSERT INTO gifi (accno,description) VALUES ('13','TOVAR');
INSERT INTO gifi (accno,description) VALUES ('19','OPRAVN� POLO�KY');
INSERT INTO gifi (accno,description) VALUES ('21','PENIAZE');
INSERT INTO gifi (accno,description) VALUES ('22','��TY V BANK�CH');
INSERT INTO gifi (accno,description) VALUES ('23','BE�N� BANKOV� �VERY');
INSERT INTO gifi (accno,description) VALUES ('24','IN� KR�TKODOB� FINAN�N� V�POMOCI');
INSERT INTO gifi (accno,description) VALUES ('25','KR�TKODOB� FINAN�N� MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('26','PREVODY MEDZI FINAN�N�MI ��TAMI');
INSERT INTO gifi (accno,description) VALUES ('29','OPRAVN� POLO�KY KU KR�TKOD. FIN. MAJETKU');
INSERT INTO gifi (accno,description) VALUES ('31','POH�AD�VKY');
INSERT INTO gifi (accno,description) VALUES ('32','Z�V�ZKY ');
INSERT INTO gifi (accno,description) VALUES ('33','Z��TOVANIE SO ZAMESTNANCAMI A IN�TIT�CIAMI');
INSERT INTO gifi (accno,description) VALUES ('34','Z��TOVANIE DAN� A DOT�CI�');
INSERT INTO gifi (accno,description) VALUES ('35','POH�AD�VKY VO�I SPOLO�N�KOM A ZDRU�ENIU');
INSERT INTO gifi (accno,description) VALUES ('36','Z�V�ZKY VO�I SPOLO�N�KOM A ZDRU�ENIU');
INSERT INTO gifi (accno,description) VALUES ('37','IN� POH�AD�VKY A Z�V�ZKY');
INSERT INTO gifi (accno,description) VALUES ('38','PRECHODN� ��TY AKT�V A PAS�V');
INSERT INTO gifi (accno,description) VALUES ('39','OPR.POL. K Z��T. VZ�AHOM A VN�TORN� Z��TOV.');
INSERT INTO gifi (accno,description) VALUES ('41','Z�KLADN� IMANIE A KAPIT�LOV� FONDY');
INSERT INTO gifi (accno,description) VALUES ('42','FONDY ZO ZISKU A PREVEDEN� HOSP. V�SLEDKY');
INSERT INTO gifi (accno,description) VALUES ('43','HOSPOD�RSKY V�SLEDOK');
INSERT INTO gifi (accno,description) VALUES ('45','REZERVY');
INSERT INTO gifi (accno,description) VALUES ('46','BANKOV� �VERY');
INSERT INTO gifi (accno,description) VALUES ('47','DLHODOB� Z�V�ZKY');
INSERT INTO gifi (accno,description) VALUES ('48','ODLO�EN� DA�');
INSERT INTO gifi (accno,description) VALUES ('49','INDIVIDU�LNY PODNIKATE�');
INSERT INTO gifi (accno,description) VALUES ('50','SPOTREBOVAN� N�KUPY');
INSERT INTO gifi (accno,description) VALUES ('51','SLU�BY');
INSERT INTO gifi (accno,description) VALUES ('52','OSOBN� N�KLADY');
INSERT INTO gifi (accno,description) VALUES ('53','DANE A POPLATKY');
INSERT INTO gifi (accno,description) VALUES ('54','IN� PREV�DZKOV� N�KLADY');
INSERT INTO gifi (accno,description) VALUES ('55','ODPISY,REZERVY A OPR. POL. PREV�DZKOV�CH N.');
INSERT INTO gifi (accno,description) VALUES ('56','FINAN�N� N�KLADY');
INSERT INTO gifi (accno,description) VALUES ('57','REZERVY A OPRAVN� POLO�KY FINAN�N�CH N.');
INSERT INTO gifi (accno,description) VALUES ('58','MIMORIADNE N�KLADY');
INSERT INTO gifi (accno,description) VALUES ('59','DANE Z PR�JMOV A PREVODOV� ��TY');
INSERT INTO gifi (accno,description) VALUES ('60','TR�BY ZA VLASTN� V�KONY A TOVAR');
INSERT INTO gifi (accno,description) VALUES ('61','ZMENA STAVU VN�TROPODNIKOV�CH Z�SOB');
INSERT INTO gifi (accno,description) VALUES ('62','AKTIV�CIA');
INSERT INTO gifi (accno,description) VALUES ('64','IN� PREV�DZKOV� V�NOSY');
INSERT INTO gifi (accno,description) VALUES ('65','Z��T. REZERV A OPR. POLO�IEK PREV�DZKOV. V.');
INSERT INTO gifi (accno,description) VALUES ('66','FINAN�N� V�NOSY');
INSERT INTO gifi (accno,description) VALUES ('67','Z��T. REZERV A OPRAVN�CH POL. FINAN�N�CH V.');
INSERT INTO gifi (accno,description) VALUES ('68','MIMORIADNE V�NOSY');
INSERT INTO gifi (accno,description) VALUES ('69','PREVODOV� ��TY');
INSERT INTO gifi (accno,description) VALUES ('70','ZA�IATO�N� A KONE�N� ��ET');
INSERT INTO gifi (accno,description) VALUES ('71','��ET ZISKOV A STR�T');
INSERT INTO gifi (accno,description) VALUES ('80','VN�TROPODNIKOV� N�KLADY');
INSERT INTO gifi (accno,description) VALUES ('90','VN�TROPODNIKOV� V�NOSY');
