-- Slovak chart of accounts
-- Peter Meszaros <peterm@insypo.sk>
--
INSERT INTO gifi (accno,description) VALUES ('01','NEHMOTNÝ INVESTIÈNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('02','HMOTNÝ INVESTIÈNÝ MAJETOK ODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('03','HMOTNÝ INVEST. MAJETOK NEODPISOVANÝ');
INSERT INTO gifi (accno,description) VALUES ('04','OBSTARANIE NEHMOTNÝCH A HM. INVESTÍCIÍ');
INSERT INTO gifi (accno,description) VALUES ('05','POSKYTNUTÉ PREDDAVKY NA NEHM. IM A HIM');
INSERT INTO gifi (accno,description) VALUES ('06','FINANÈNÉ INVESTÍCIE');
INSERT INTO gifi (accno,description) VALUES ('07','OPRÁVKY K NEHMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('08','OPRÁVKY K HMOTNÉMU IM');
INSERT INTO gifi (accno,description) VALUES ('09','OPRAVNÉ POLO®KY K IM');
INSERT INTO gifi (accno,description) VALUES ('11','MATERIÁL');
INSERT INTO gifi (accno,description) VALUES ('12','ZÁSOBY VLASTNEJ VÝROBY');
INSERT INTO gifi (accno,description) VALUES ('13','TOVAR');
INSERT INTO gifi (accno,description) VALUES ('19','OPRAVNÉ POLO®KY');
INSERT INTO gifi (accno,description) VALUES ('21','PENIAZE');
INSERT INTO gifi (accno,description) VALUES ('22','ÚÈTY V BANKÁCH');
INSERT INTO gifi (accno,description) VALUES ('23','BE®NÉ BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('24','INÉ KRÁTKODOBÉ FINANÈNÉ VÝPOMOCI');
INSERT INTO gifi (accno,description) VALUES ('25','KRÁTKODOBÝ FINANÈNÝ MAJETOK');
INSERT INTO gifi (accno,description) VALUES ('26','PREVODY MEDZI FINANÈNÝMI ÚÈTAMI');
INSERT INTO gifi (accno,description) VALUES ('29','OPRAVNÉ POLO®KY KU KRÁTKOD. FIN. MAJETKU');
INSERT INTO gifi (accno,description) VALUES ('31','POH¥ADÁVKY');
INSERT INTO gifi (accno,description) VALUES ('32','ZÁVÄZKY ');
INSERT INTO gifi (accno,description) VALUES ('33','ZÚÈTOVANIE SO ZAMESTNANCAMI A IN©TITÚCIAMI');
INSERT INTO gifi (accno,description) VALUES ('34','ZÚÈTOVANIE DANÍ A DOTÁCIÍ');
INSERT INTO gifi (accno,description) VALUES ('35','POH¥ADÁVKY VOÈI SPOLOÈNÍKOM A ZDRU®ENIU');
INSERT INTO gifi (accno,description) VALUES ('36','ZÁVÄZKY VOÈI SPOLOÈNÍKOM A ZDRU®ENIU');
INSERT INTO gifi (accno,description) VALUES ('37','INÉ POH¥ADÁVKY A ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('38','PRECHODNÉ ÚÈTY AKTÍV A PASÍV');
INSERT INTO gifi (accno,description) VALUES ('39','OPR.POL. K ZÚÈT. VZ«AHOM A VNÚTORNÉ ZÚÈTOV.');
INSERT INTO gifi (accno,description) VALUES ('41','ZÁKLADNÉ IMANIE A KAPITÁLOVÉ FONDY');
INSERT INTO gifi (accno,description) VALUES ('42','FONDY ZO ZISKU A PREVEDENÉ HOSP. VÝSLEDKY');
INSERT INTO gifi (accno,description) VALUES ('43','HOSPODÁRSKY VÝSLEDOK');
INSERT INTO gifi (accno,description) VALUES ('45','REZERVY');
INSERT INTO gifi (accno,description) VALUES ('46','BANKOVÉ ÚVERY');
INSERT INTO gifi (accno,description) VALUES ('47','DLHODOBÉ ZÁVÄZKY');
INSERT INTO gifi (accno,description) VALUES ('48','ODLO®ENÁ DAÒ');
INSERT INTO gifi (accno,description) VALUES ('49','INDIVIDUÁLNY PODNIKATE¥');
INSERT INTO gifi (accno,description) VALUES ('50','SPOTREBOVANÉ NÁKUPY');
INSERT INTO gifi (accno,description) VALUES ('51','SLU®BY');
INSERT INTO gifi (accno,description) VALUES ('52','OSOBNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('53','DANE A POPLATKY');
INSERT INTO gifi (accno,description) VALUES ('54','INÉ PREVÁDZKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('55','ODPISY,REZERVY A OPR. POL. PREVÁDZKOVÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('56','FINANÈNÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('57','REZERVY A OPRAVNÉ POLO®KY FINANÈNÝCH N.');
INSERT INTO gifi (accno,description) VALUES ('58','MIMORIADNE NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('59','DANE Z PRÍJMOV A PREVODOVÉ ÚÈTY');
INSERT INTO gifi (accno,description) VALUES ('60','TR®BY ZA VLASTNÉ VÝKONY A TOVAR');
INSERT INTO gifi (accno,description) VALUES ('61','ZMENA STAVU VNÚTROPODNIKOVÝCH ZÁSOB');
INSERT INTO gifi (accno,description) VALUES ('62','AKTIVÁCIA');
INSERT INTO gifi (accno,description) VALUES ('64','INÉ PREVÁDZKOVÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('65','ZÚÈT. REZERV A OPR. POLO®IEK PREVÁDZKOV. V.');
INSERT INTO gifi (accno,description) VALUES ('66','FINANÈNÉ VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('67','ZÚÈT. REZERV A OPRAVNÝCH POL. FINANÈNÝCH V.');
INSERT INTO gifi (accno,description) VALUES ('68','MIMORIADNE VÝNOSY');
INSERT INTO gifi (accno,description) VALUES ('69','PREVODOVÉ ÚÈTY');
INSERT INTO gifi (accno,description) VALUES ('70','ZAÈIATOÈNÝ A KONEÈNÝ ÚÈET');
INSERT INTO gifi (accno,description) VALUES ('71','ÚÈET ZISKOV A STRÁT');
INSERT INTO gifi (accno,description) VALUES ('80','VNÚTROPODNIKOVÉ NÁKLADY');
INSERT INTO gifi (accno,description) VALUES ('90','VNÚTROPODNIKOVÉ VÝNOSY');
--