-- Slovak chart of accounts
-- Peter Meszaros <peterm@insypo.sk>
-- Kompletná úètová osnova platná v roku 2007
--
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('01','NEHMOTNÝ INVESTIÈNÝ MAJETOK','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('02','HMOTNÝ INVESTIÈNÝ MAJETOK ODPISOVANÝ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('03','HMOTNÝ INVEST. MAJETOK NEODPISOVANÝ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('04','OBSTARANIE NEHMOTNÝCH A HM. INVESTÍCIÍ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('05','POSKYTNUTÉ PREDDAVKY NA NEHM. IM A HIM','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('06','FINANÈNÉ INVESTÍCIE','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('07','OPRÁVKY K NEHMOTNÉMU IM','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('08','OPRÁVKY K HMOTNÉMU IM','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('09','OPRAVNÉ POLO®KY K IM','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('11','MATERIÁL','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('12','ZÁSOBY VLASTNEJ VÝROBY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('13','TOVAR','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('19','OPRAVNÉ POLO®KY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('21','PENIAZE','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('22','ÚÈTY V BANKÁCH','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('23','BE®NÉ BANKOVÉ ÚVERY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('24','INÉ KRÁTKODOBÉ FINANÈNÉ VÝPOMOCI','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('25','KRÁTKODOBÝ FINANÈNÝ MAJETOK','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('26','PREVODY MEDZI FINANÈNÝMI ÚÈTAMI','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('29','OPRAVNÉ POLO®KY KU KRÁTKOD. FIN. MAJETKU','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('31','POH¥ADÁVKY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('32','ZÁVÄZKY ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('33','ZÚÈTOVANIE SO ZAMESTNANCAMI A IN©TITÚCIAMI','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('34','ZÚÈTOVANIE DANÍ A DOTÁCIÍ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('35','POH¥ADÁVKY VOÈI SPOLOÈNÍKOM A ZDRU®ENIU','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('36','ZÁVÄZKY VOÈI SPOLOÈNÍKOM A ZDRU®ENIU','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('37','INÉ POH¥ADÁVKY A ZÁVÄZKY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('38','PRECHODNÉ ÚÈTY AKTÍV A PASÍV','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('39','OPR.POL. K ZÚÈT. VZ«AHOM A VNÚTORNÉ ZÚÈTOV.','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('41','ZÁKLADNÉ IMANIE A KAPITÁLOVÉ FONDY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('42','FONDY ZO ZISKU A PREVEDENÉ HOSP. VÝSLEDKY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('43','HOSPODÁRSKY VÝSLEDOK','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('45','REZERVY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('46','BANKOVÉ ÚVERY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('47','DLHODOBÉ ZÁVÄZKY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('48','ODLO®ENÁ DAÒ','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('49','INDIVIDUÁLNY PODNIKATE¥','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('50','SPOTREBOVANÉ NÁKUPY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('51','SLU®BY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('52','OSOBNÉ NÁKLADY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('53','DANE A POPLATKY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('54','INÉ PREVÁDZKOVÉ NÁKLADY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('55','ODPISY,REZERVY A OPR. POL. PREVÁDZKOVÝCH N.','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('56','FINANÈNÉ NÁKLADY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('57','REZERVY A OPRAVNÉ POLO®KY FINANÈNÝCH N.','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('58','MIMORIADNE NÁKLADY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('59','DANE Z PRÍJMOV A PREVODOVÉ ÚÈTY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('60','TR®BY ZA VLASTNÉ VÝKONY A TOVAR','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('61','ZMENA STAVU VNÚTROPODNIKOVÝCH ZÁSOB','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('62','AKTIVÁCIA','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('64','INÉ PREVÁDZKOVÉ VÝNOSY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('65','ZÚÈT. REZERV A OPR. POLO®IEK PREVÁDZKOV. V.','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('66','FINANÈNÉ VÝNOSY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('67','ZÚÈT. REZERV A OPRAVNÝCH POL. FINANÈNÝCH V.','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('68','MIMORIADNE VÝNOSY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('69','PREVODOVÉ ÚÈTY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('70','ZAÈIATOÈNÝ A KONEÈNÝ ÚÈET','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('71','ÚÈET ZISKOV A STRÁT','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('80','VNÚTROPODNIKOVÉ NÁKLADY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('90','VNÚTROPODNIKOVÉ VÝNOSY','H','\N','\N','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('010000','Dlhodobý nehmotný majetok','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('011000','Zriaïovacie výdavky','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('012000','Aktivované náklady na vývoj','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('013000','Softvér','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('014000','Ocenitelné práva','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('015000','Goodwill','A','01','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('019000','Ostatný nehmotný investièný majetok','A','01','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('020000','Dlhodobý hmotný majetok - odpisovaný','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('021000','Stavby','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('022000','Samostatne hnutelné veci','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('025000','Pestovatelské celky trvalých porastov','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('026000','Základné stádo a ú¾itkové zvieratá','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('029000','Ostatný dlhodobý hmotný majetok','A','02','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('030000','Dlhodobý hmotný majetok - neodpisovaný','A','03','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('031000','Pozemky','A','03','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('032000','Umelecké diela a zbierky','A','03','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('040000','Obstaranie dlhodobého majetku','A','04','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('041000','Obstaranie dlhodobého nehmotného majetku','A','04','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('042000','Obstaranie dlhodobého hmotného majetku','A','04','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('043000','Obstaranie dlhodobého finanèného majetku','A','04','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('050000','Poskytnuté preddavky na dlhodobý majetok','A','05','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('051000','Poskytnuté preddavky na nehmot. majetok','A','05','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('052000','Poskytnuté preddavky na hmotný  majetok','A','05','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('053000','Poskytnuté preddavky na finaèný majetok','A','05','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('060000','Dlhodobý finanèný majetok','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('061000','Podiel.cenné papiere a podiely v ovl.os.','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('062000','Podiel.cenné papiere a podiely s podstat','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('063000','Realizovateåné cenné papiere a podiely','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('065000','Dlhové cenné papiere dr¾ané do splatnost','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('066000','Pozièky uètov.jednotke v konsolid.celku','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('067000','Ostatné pô¾ièky','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('069000','Ostaný dlhodobý finanèný majetok','A','06','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('070000','Oprávky k dlhodobému nehmotnému majetku','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('071000','Oprávky k zriadovacím nákladom','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('072000','Oprávky k aktivovaným nákladom na vývoj','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('073000','Oprávky k softvéru','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('074000','Oprávky k ocenitelným právam','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('075000','Oprávky ku goodwillu','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('079000','Oprávky k ostatnému drob.nehmot.majetku','A','07','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('080000','Oprávky k dlhodobému hmotnému majetku','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('081000','Oprávky k stavbám','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('082000','Oprávky k samostatným hnutelným veciam','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('085000','Oprávky k pestovatelským celkom a poras.','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('086000','Oprávky k základ.stádu a ú¾itkovým zvier','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('089000','Oprávky k ostat.dlhodob.hmotnému majetku','A','08','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('090000','Opravné polo¾ky k dlhodobému majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('091000','Opravná polo¾ka k dlhodob.nehmot.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('092000','Opravná polo¾ka k dlhodob.hmot.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('093000','Opravná polo¾ka k nedok.nehmot.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('094000','Opravná polo¾ka k nedok.hmot.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('095000','Opravná polo¾ka k poskytnutým preddavkom','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('096000','Opravná polo¾ka k dlhodob.finanè.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('097000','Opravná polo¾ka k nadobudnutému majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('098000','Oprávky k opr.polo¾ke k nadobud.majetku','A','09','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('110000','Materiál','A','11','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('111000','Obstaranie materiálu','A','11','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('111600','Nákup zvierat','A','11','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('112000','Materiál na sklade','A','11','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('119000','Materiál na ceste','A','11','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('120000','Zásoby vlastnej výroby','A','12','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('121000','Nedokonèená výroba','A','12','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('122000','Polotovary vlastnej výroby','A','12','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('123000','Výrobky','A','12','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('124000','Zvieratá','A','12','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('130000','Tovar','A','13','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('131000','Obstaranie tovaru','A','13','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('132000','Tovar na sklade a v predajniach','A','13','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('139000','Tovar na ceste','A','13','A','IC');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('190000','Opravné polo¾ky k zásobám','A','19','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('191000','Opravná polo¾ka k materialu','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('192000','Opravná polo¾ka k nedokonèenej výrobe','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('193000','Opravná polo¾ka k polotovarom vl.vyroby','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('194000','Opravná polo¾ka k výrobkom','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('195000','Opravná polo¾ka k zvieratám','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('196000','Opravná polo¾ka k tovaru','A','19','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('210000','Peniaze','A','21','A','AR_paid:AP_paid');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('211000','Pokladnica','A','21','A','AR_paid:AP_paid');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('213000','Ceniny','A','21','A','AR_paid:AP_paid');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('220000','Úèty v bankách','A','22','A','AR_paid:AP_paid');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('221000','Bankové úèty','A','22','A','AR_paid:AP_paid');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('230000','Be¾né bankové úvery','A','23','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('231000','Krátkodobé bankové úvery','A','23','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('232000','Eskontné úvery','A','23','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('240000','Iné krátkodobé finanèné výpomoci','A','24','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('241000','Emitované krátkodobé dlhopisy','A','24','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('249000','Ostatné krátkodobé finanèné vypomoci','A','24','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('250000','Krátkodobý finanèný majetok','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('251000','Majetkové cenné papiere na ochodovanie','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('252000','Vlastné akcie a vlastné obchodné podiely','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('253000','Dlhové cenné papiere na obchodovanie','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('255000','Vlastné dlhopisy','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('256000','Dlhové cenné papiere so splat.do 1 roka','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('257000','Ostatné realizovateµne cenné papiere','A','25','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('260000','Prevody medzi finanènými úètami','A','26','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('261000','Peniaze na ceste','A','26','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('290000','Opravná polo¾ka ku krátkodob.finan.maj.','A','29','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('291000','Opravná polo¾ka ku krátkodob.finanè.maj.','A','29','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('311000','Odberatelia','A','31','A','AR');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('312000','Zmenky na inkaso','A','31','A','AR');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('313000','Pohladávky za eskontné cenné papiere','A','31','A','AR');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('314000','Poskytnuté preddavky','A','31','A','AR');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('315000','Ostané pohladávky','A','31','A','AR');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('321000','Dodavatelia','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('322000','Zmenky na úhradu','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('323000','Krátkodobé rezervy','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('324000','Prijaté preddavky','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('325000','Ostatné záväzky','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('326000','Nevyfaktúrované dodávky','A','32','L','AP');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('331000','Zamestnanci','A','33','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('333000','Ostatné záväzky voèi zamenstnancom','A','33','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('335000','Pohladávky voèi zamestnancom','A','33','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('336000','Zuètovanie s in¹.soc.zabezpeèenia a zdr.','A','33','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('341000','Daò z príjmov','A','34','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('342000','Ostané priame dane','A','34','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343000','Daò z pridanej hodnoty','A','34','L','IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343100','Vstupná daò z pridanej hodnoty','A','34','L','AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343110','Vstupná daò PH 10%','A','34','L','AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343120','Vstupná daò PH 19%','A','34','L','AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343200','Výstupná daò z pridanej hodnoty','A','34','L','AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343210','Výstupná daò PH 10%','A','34','L','AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343220','Výstupná daò PH 19%','A','34','L','AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343900','Ostatné zuètovanie dane z prid. hodnoty','A','34','L','IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343910','Vstupná daò PH na ceste 10%','A','34','A','IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('343920','Vstupná DPH na ceste 19 %','A','34','A','IC_taxpart:IC_taxservice');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('345000','Ostane dane a poplatky','A','34','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('346000','Dotácie zo ¹tátneho rozpoètu','A','34','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('347000','Ostatné dotácie','A','34','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('351000','Pohladávky v rámci konsolidovaného celku','A','35','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('353000','Pohladávky za upísané vlastné imanie','A','35','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('354000','Pohl.voèi spoloèníkom pri úhrade straty','A','35','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('355000','Ostatné pohladávky voèi spoloèníkom','A','35','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('358000','Pohladávky voèi úèastníkom zdru¾enia','A','35','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('361000','Záväzky v rámci konsolidovaného celku','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('364000','Záväzky voèi spoloè. pri rozdel. zisku','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('365000','Ostatné záväzky voèi spoloèníkom','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('366000','Záväz.voèi spoloèníkom zo závislej èinn.','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('367000','Záväzky z upisaných nespl.cenných papier','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('368000','Záväzky voèi uèastníkom zdru¾enia','A','36','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('371000','Pohladávky z predaja podniku','A','37','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('372000','Záväzky z predaja podniku','A','37','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('373000','Pohladávky a záväzky z pevných termin.op','A','37','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('374000','Pohladávky z prenájmu','A','37','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('375000','Pohladávky z emitovaných dlhopisov','A','37','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('376000','Nakupné opcie','A','37','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('377000','Predajné opcie','A','37','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('378000','Iné pohladávky','A','37','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('379000','Iné záväzky','A','37','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('381000','Náklady budúcich období','A','38','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('382000','Komplexné náklady budúcich období','A','38','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('383000','Výdavky budúcich období','A','38','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('384000','Výnosy budúcich období','A','38','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('385000','Príjmy budúcich období','A','38','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('391000','Opravná polo¾ka k pohladávkam','A','39','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('395000','Vnútorné zúètovanie','A','39','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('398000','Spojovací úèet pri zdru¾ení','A','39','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('411000','Základné imanie','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('412000','Emisné á¾io','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('413000','Ostatné kapitálové fondy','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('414000','Oceòovacie rozdiely z precenenia majetku','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('415000','Oceòovacie rozdiely z kapitálových uèas.','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('416000','Oceò.rozdiely z precenenia pri splyn.roz','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('417000','Zákonný rezervný fond z kapitál.vkladov','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('418000','Nedelitelný fond z kapitálových vkladov','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('419000','Zmeny základného imania','A','41','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('421000','Zákonný rezervný fond','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('422000','Nedelitelný fond','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('423000','©tatutárne fondy','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('427000','Ostatné fondy','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('428000','Nerozdelený zisk  minulých rokov','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('429000','Neuhradená strata minulých rokov','A','42','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('431000','Hospodársky výsledok v schvaåovac.konaní','A','43','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('451000','Rezervy zákonné','A','45','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('459000','Ostatné rezervy','A','45','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('461000','Bankové úvery','A','46','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('471000','Dlhodobé záväzky v rámci konsolid.celku','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('472000','Záväzky zo socialného fondu','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('473000','Emitované dlhopisy','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('474000','Záväzky z prenájmu','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('475000','Dlhodobé prijaté preddavky','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('476000','Dlhodobé nevyfakturované dodávky','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('478000','Dlhodobé zmenky na úhradu','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('479000','Ostatné dlhodobé záväzky','A','47','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('481000','Odlo¾ený daòový záväzok a pohladávka','A','48','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('491000','Vlastné imanie fyzickej osoby','A','49','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('500000','Spotrebované nákupy','A','50','E','AP_amount:IC_cogs');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('501000','Spotreba materiálu','A','50','E','AP_amount:IC_cogs');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('502000','Spotreba energie','A','50','E','AP_amount:IC_cogs');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('503000','Spotreba ostatných neskladovatel.dodávok','A','50','E','AP_amount:IC_cogs');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('504000','Predaný tovar','A','50','E','AP_amount:IC_cogs');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('510000','Slu¾by','A','51','E','AP_amount:IC_expense');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('511000','Opravy a udr¾ovanie','A','51','E','AP_amount:IC_expense');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('512000','Cestovné','A','51','E','AP_amount:IC_expense');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('513000','Náklady na reprezentáciu','A','51','E','AP_amount:IC_expense');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('518000','Ostatné slu¾by','A','51','E','AP_amount:IC_expense');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('520000','Osobné náklady','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('521000','Mzdové náklady','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('522000','Príjmy spoloèníkov zo závislej èinnosti','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('523000','Odmeny èlenom orgánov spoloè. a dru¾stva','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('524000','Zákonné sociálne poistenie','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('525000','Ostatné sociálne poistenie','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('526000','Sociálne náklady fyzickej osoby','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('527000','Zákonné sociálne náklady','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('528000','Ostatné sociálne náklady','A','52','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('530000','Dane a poplatky','A','53','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('531000','Cestná daò','A','53','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('532000','Daò z nehnutelnosti','A','53','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('538000','Ostatné dane a poplatky','A','53','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('540000','Iné náklady z hospodárskej èinnosti','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('541000','Zostat.cena predaného nehmot.a hmot.maj.','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('542000','Predaný material','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('543000','Dary','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('544000','Zmluvné pokuty a penále','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('545000','Ostatné pokuty a penále a úroky z ome¹k.','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('546000','Odpis pohladávky','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('548000','Ostatné náklady z hospodárskej èinnosti','A','54','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('551000','Odpisy dlhodobého nehm.a hmotn.majetku','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('552000','Tvorba zákonných rezerv','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('554000','Tvorba ostatných rezerv','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('555000','Zuètovanie komplex.nákladov bud.období','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('557000','Zuètovanie oprávky k opr.polo¾. k nadob','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('558000','Tvorba opravných polo¾iek','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('559000','Tvorba ostatných opravných polo¾iek','A','55','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('560000','Finanèné náklady','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('561000','Predané cenné papiere a podiely','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('562000','Úroky','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('563000','Kurzové straty','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('564000','Náklady na precenenie cenných papierov','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('566000','Náklady na krátkodobý finanèný majetok','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('567000','Náklady na derivátové operácie','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('568000','Ostatné finanèné náklady','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('569000','Manká a ¹kody na finanènom majetku','A','56','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('574000','Tvorba rezerv','A','57','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('579000','Tvorba opravných polo¾iek','A','57','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('580000','Mimoriadne náklady','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('581000','Náklady na zmenu metódy','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('582000','©kody','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('584000','Tvorba rezerv','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('588000','Ostatné mimoriadné náklady','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('589000','Tvorba opravných polo¾iek','A','58','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('591000','Daò z príjmov z be¾nej èinn. - splatná','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('592000','Daò z príjmov z be¾nej èinn. - odlo¾ená','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('593000','Daò z príjmov z mim.èinnosti - splatná','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('594000','Daò z príjmov z mim.èinnosti - odlo¾ená','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('595000','Dodatoèné odvody dane z príjmov','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('596000','Prevod podielov na hosp.výsl.spoloèníkom','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('597000','Prevod nákladov hospodárskej èinnosti','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('598000','Prevod finanèných nákladov','A','59','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('600000','Tr¾by za vlastné vykony a tovar','A','60','I','AR_amount:IC_sale:IC_income');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('601000','Tr¾by za vlastné výrobky','A','60','I','AR_amount:IC_sale:IC_income');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('602000','Tr¾by z predaja slu¾ieb','A','60','I','AR_amount:IC_sale:IC_income');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('604000','Tr¾by za tovar','A','60','I','AR_amount:IC_sale');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('610000','Zmena stavu vnútroorganizaèných zásob','A','61','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('611000','Zmena stavu nedokonèenej výroby','A','61','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('612000','Zmena stavu polotovarov','A','61','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('613000','Zmena stavu výrobkov','A','61','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('614000','Zmena stavu zvierat','A','61','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('620000','Aktivácia','A','62','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('621000','Aktivácia materiálu a tovaru','A','62','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('622000','Aktivácia vnútroorganizaèných slu¾ieb','A','62','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('623000','Aktivácia dlhodobého nehmotného majetku','A','62','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('624000','Aktivácia dlhodobého hmotného majetku','A','62','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('640000','Ostatné výnosy z hospodárskej èinnosti','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('641000','Tr¾by z predaja dlh.nehm.a hmotn.majetku','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('642000','Tr¾by z predaja materiálu','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('644000','Zmluvné pokuty,penále a úroky z ome¹kan.','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('645000','Ostatné pokuty,penále a úroky z ome¹kan.','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('646000','Výnosy z odpísaných pohladávok','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('648000','Ostatné výnosy z hospodárskej èinnosti','A','64','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('652000','Zúètovanie zákonných rezerv','A','65','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('654000','Zúètovanie ostatných rezerv','A','65','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('655000','Zúètovanie komplexn.nákladov bud.obdobi','A','65','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('657000','Zúètov.oprávok k opr.polo¾ke k nadob.maj','A','65','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('659000','Zúètovanie opravných polo¾iek','A','65','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('660000','Finanèné výnosy','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('661000','Tr¾by z predaja cenných papierov a podie','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('662000','Úroky','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('663000','Kurzové zisky','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('664000','Výnosy z precenenia cenných papierov','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('665000','Výnosy z dlhodobého finanèného majetku','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('666000','Výnosy z krátkodob. finanèného majetku','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('667000','Výnosy z derivátových operácií','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('668000','Ostatné finanèné výnosy','A','66','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('674000','Zúètovanie rezerv','A','67','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('679000','Zúètovanie opravných polo¾iek','A','67','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('680000','Mimoriadne výnosy','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('681000','Výnosy zo zmeny metódy','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('682000','Náhrady ¹kôd','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('684000','Zúètovanie rezerv','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('688000','Ostané mimoriadne výnosy','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('689000','Zúètovanie opravných polo¾iek','A','68','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('697000','Prevod výnosov z hospodárskej èinnosti','A','69','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('698000','Prevod finanèných výnosov','A','69','I','AR_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('701000','Zaèiatoèný úèet súvahový','A','70','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('702000','Koneèný úèet súvahový','A','70','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('710000','Úèet ziskov a strát','A','71','L','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('751000','Prenajatý majetok','A','75','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('799000','Zúètovací podsúvahový úèet','A','79','A','\N');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('800000','Vnútropodnikové náklady','A','80','E','AP_amount');
INSERT INTO chart (accno,description,charttype,gifi_accno,category,link) VALUES ('900000','Vnútropodnikové výnosy','A','90','I','AR_amount');
--
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '343120'),0.19);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '343220'),0.19);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '343110'),0.10);
INSERT INTO tax (chart_id,rate) VALUES ((select id from chart where accno = '343210'),0.10);
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '132000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '604000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '504000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '663000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '563000'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, prec) VALUES (1,'SKK',2);
INSERT INTO curr (rn, curr, prec) VALUES (2,'EUR',2);
INSERT INTO curr (rn, curr, prec) VALUES (3,'CZK',2);

