-- Swiss German chart of accounts UTF-8
-- Kontenrahmen für KMU in Produktion, Handel und Dienstleistungen
--
-- Tekki, 2010-12-28

 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1', 'AKTIVEN', 'H', '1', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('10', 'Umlaufvermögen', 'H', '1', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('100', 'Flüssige Mittel und Wertschriften', 'H', '10', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1000', 'Kasse', 'A', '100', 'A', 'AR_paid:AP_paid');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1010', 'Post', 'A', '100', 'A', 'AR_paid:AP_paid');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1020', 'Bank', 'A', '100', 'A', 'AR_paid:AP_paid');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1040', 'Checks, Besitzwechsel', 'A', '100', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1050', 'Kurzfristige Geldanlagen', 'A', '100', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1060', 'Wertschriften', 'A', '100', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('110', 'Forderungen', 'H', '10', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1100', 'Debitoren', 'A', '110', 'A', 'AR');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1109', 'Delkredere', 'A', '110', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1130', 'Kurzfristige Aktivdarlehen', 'A', '110', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1140', 'Vorauszahlungen an Lieferanten', 'A', '110', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1171', 'MWST Vorsteuer auf Aufwand 2.5 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1172', 'MWST Vorsteuer auf Aufwand 3.8 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1173', 'MWST Vorsteuer auf Aufwand 8.0 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1174', 'MWST Vorsteuer auf Investitionen 8.0 %', 'A', '110', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1176', 'Verrechnungssteuer', 'A', '110', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('120', 'Vorräte', 'H', '10', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1200', 'Handelswaren', 'A', '120', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1210', 'Rohmaterial', 'A', '120', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1220', 'Fertigfabrikate', 'A', '120', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1280', 'Angefangene Arbeiten', 'A', '120', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('130', 'Aktive Rechnungsabgrenzung', 'H', '10', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1300', 'Transitorische Aktiven', 'A', '130', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('14', 'Anlagevermögen', 'H', '1', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('140', 'Finanzanlagen', 'H', '14', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1400', 'Wertpapiere', 'A', '140', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1410', 'Beteiligungen', 'A', '140', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1420', 'Langfristige Aktivdarlehen', 'A', '140', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1430', 'Aktivhypotheken', 'A', '140', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1440', 'Andere Finanzanlagen', 'A', '140', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('150', 'Mobile Sachanlagen', 'H', '14', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1500', 'Maschinen, Produktionsanlagen', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1509', 'WB Maschinen Produktion', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1510', 'Mobiliar und Einrichtungen', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1519', 'WB Mobiliar und Einrichtungen', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1520', 'Büromaschinen, EDV', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1529', 'WB Büromaschinen, EDV', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1530', 'Fahrzeuge', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1539', 'WB Fahrzeuge', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1540', 'Werkzeuge und Geräte', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1549', 'WB Werkzeuge und Geräte', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1550', 'Lagereinrichtungen', 'A', '150', 'A', 'IC');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1559', 'WB Lagereinrichtungen', 'A', '150', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('160', 'Immobile Sachanlagen', 'H', '14', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1600', 'Immobilien', 'A', '160', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1609', 'WB Immobilien', 'A', '160', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('170', 'Immaterielle Sachanlagen', 'H', '14', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1700', 'Patente', 'A', '170', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1709', 'WB Patente', 'A', '170', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1710', 'Marken', 'A', '170', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1719', 'WB Marken', 'A', '170', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1720', 'Lizenzen', 'A', '170', 'A', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1729', 'WB Lizenzen', 'A', '170', 'A', '', '1');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2', 'PASSIVEN', 'H', '2', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('20', 'Kurzfristiges Fremdkapital', 'H', '2', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('200', 'Kf. Verbindlichkeiten aus Lieferungen und Leistungen', 'H', '20', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2000', 'Kreditoren', 'A', '200', 'L', 'AP');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2011', 'MWST 2.5 %', 'A', '200', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2012', 'MWST 3.8 %', 'A', '200', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2013', 'MWST 8.0 %', 'A', '200', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2020', 'Kreditoren Sozialversicherungen', 'A', '200', 'L', 'AP');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2030', 'Vorauszahlungen von Kunden', 'A', '200', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('210', 'Kf. Finanzverbindlichkeiten', 'H', '20', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2100', 'Bank Kontokorrent', 'A', '210', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2110', 'Schuldwechsel', 'A', '210', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2120', 'Kurzfristige Darlehen', 'A', '210', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('220', 'Andere kf. Verbindlichkeiten', 'H', '20', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2200', 'Dividenden, Tantiemen', 'A', '220', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('230', 'Passive Rechnungsabgrenzung', 'H', '20', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2300', 'Transitorische Passiven', 'A', '230', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2310', 'Kurzfristige Rückstellungen', 'A', '230', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('24', 'Langfristiges Fremdkapital', 'H', '2', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('240', 'Langfristige Finanzverbindlichkeiten', 'H', '24', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2400', 'Langfristige Darlehen', 'A', '240', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2410', 'Hypotheken', 'A', '240', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2460', 'Obligationenanleihen', 'A', '240', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('260', 'Lanfristige Rückstellungen', 'H', '24', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2600', 'Langfristige Rückstellungen', 'A', '260', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('28', 'Eigenkapital', 'H', '2', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('280', 'Grundkapital', 'H', '28', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2800', 'Stammkapital', 'A', '280', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2810', 'Partizipationskapital', 'A', '280', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('290', 'Reserven, Bilanzgewinn', 'H', '28', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2900', 'Gesetzliche Reserven', 'A', '290', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2910', 'Andere Reserven', 'A', '290', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2990', 'Gewinn-/Verlustvortrag', 'A', '290', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2995', 'Jahresgewinn', 'A', '290', 'L', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3', 'BETRIEBSERTRAG AUS LIEFERUNGEN UND LEISTUNGEN', 'H', '3', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3000', 'Produktertrag', 'A', '3', 'I', 'AR_amount:IC_sale');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3090', 'Beständesänderung angefangene und fertige Arbeiten', 'A', '3', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3200', 'Handelsertrag', 'A', '3', 'I', 'AR_amount:IC_sale');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3400', 'Dienstleistungsertrag', 'A', '3', 'I', 'AR_amount:IC_income');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3600', 'Übriger Betriebsertrag', 'A', '3', 'I', 'AR_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3900', 'Debitorenverluste', 'A', '3', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3950', 'Wechselkursertrag', 'A', '3', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3955', 'Wechselkursverlust', 'A', '3', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4', 'AUFWAND FÜR MATERIAL, WAREN UND DIENSTLEISTUNGEN', 'H', '4', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4000', 'Materialaufwand', 'A', '4', 'E', 'IC_cogs');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4200', 'Handelswarenaufwand', 'A', '4', 'E', 'IC_cogs');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4400', 'Aufwand für Dienstleistungen', 'A', '4', 'E', 'IC_expense');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5', 'PERSONALAUFWAND', 'H', '5', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5000', 'Lohnaufwand', 'A', '5', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5700', 'Sozialversicherungsaufwand', 'A', '5', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5800', 'Übriger Personalaufwand', 'A', '5', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6', 'SONSTIGER BETRIEBSAUFWAND', 'H', '6', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6000', 'Raumaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6100', 'Unterhalt, Reparaturen, Ersatz', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6200', 'Fahrzeugaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6300', 'Versicherungsaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6400', 'Energie- und Entsorgungsaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6500', 'Verwaltungs- und Informatikaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6600', 'Werbeaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6700', 'Übriger Betriebsaufwand', 'A', '6', 'E', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('68', 'Finanzerfolg', 'H', '6', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6800', 'Zinsaufwand', 'A', '68', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6850', 'Zinsertrag', 'A', '68', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('69', 'Abschreibungen', 'H', '6', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6900', 'Abschreibungen', 'A', '69', 'E', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7', 'BETRIEBLICHE NEBENERFOLGE', 'H', '7', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('74', 'Erfolg aus Finanzanlagen', 'H', '7', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7400', 'Nebenbetrieblicher Zinsertrag', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7410', 'Nebenbetrieblicher Zinsaufwand', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7420', 'Wertschriftenertrag', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7430', 'Wertschriftenaufwand', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7440', 'Beteiligungsertrag', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7450', 'Beteiligungsaufwand', 'A', '74', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('75', 'Liegenschaftenerfolg', 'H', '7', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7500', 'Liegenschaftenerfolg', 'A', '75', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7510', 'Liegenschaftenaufwand', 'A', '75', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('79', 'Gewinne aus Veräusserung von Anlagevermögen', 'H', '7', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7900', 'Gewinne aus Veräusserung von Anlagevermögen', 'A', '79', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8', 'AUSSERORDENTLICHER  ERFOLG, STEUERN', 'H', '8', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('80', 'Ausserordentlicher  Erfolg', 'H', '8', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8000', 'Ausserordentlicher Ertrag', 'A', '80', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8010', 'Ausserordentlicher Aufwand', 'A', '80', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('82', 'Betriebsfremder Erfolg', 'H', '8', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8200', 'Betriebsfremder Ertrag', 'A', '82', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8210', 'Betriebsfremder Aufwand', 'A', '82', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('89', 'Steuern', 'H', '8', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8900', 'Steuern', 'A', '89', 'I', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9', 'ABSCHLUSS', 'H', '9', 'I', '');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9000', 'Erfolgsrechnung', 'A', '9', 'I', 'AP_amount');
 INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9100', 'Bilanz', 'A', '9', 'I', 'AP_amount');
--
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1171'),0.025);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1172'),0.038);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1173'),0.080);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1174'),0.080);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2011'),0.025);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2012'),0.038);
 INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2013'),0.080);
--
 INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1200'));
 INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '3200'));
 INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '4200'));
 INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '3950'));
 INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '3955'));
 INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
 INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
 INSERT INTO curr (rn, curr, precision) VALUES (1,'CHF',2);
 INSERT INTO curr (rn, curr, precision) VALUES (2,'EUR',2);
 INSERT INTO curr (rn, curr, precision) VALUES (3,'USD',2);
