-- Swiss French chart of accounts UTF-8
-- Cadres comptables suisses pour les petites et moyennes entreprises dans la production, le commerce et les services
--
-- Tekki, 2012-02-12
--
SET client_encoding = 'UTF-8';
--
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1', 'ACTIFS', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('10', 'Actifs circulants', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('100', 'Liquidités et titres', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1000', 'Caisse', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1010', 'Poste', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1020', 'Banque', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1040', 'Chèques, effets à recevoir', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1050', 'Placement d\'argent à court terme', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1060', 'Titres à court terme', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('110', 'Créances', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1100', 'Débiteurs', 'A', '110', 'A', 'AR');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1109', 'Durcroire', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1130', 'Prêts actifs à court terme', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1140', 'Paiement anticipé fournisseurs', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1171', 'TVA impôt préalable charges 2.5 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1172', 'TVA impôt préalable charges 3.8 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1173', 'TVA impôt préalable charges 8.0 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1174', 'TVA impôt préalable investitions 8.0 %', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1176', 'Impôt anticipé', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('120', 'Stocks', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1200', 'Marchandises commerciales', 'A', '120', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1210', 'Matières premières', 'A', '120', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1220', 'Produits finis', 'A', '120', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1280', 'Travaux commencés', 'A', '120', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('130', 'Actifs transitoires', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1300', 'Actifs transitoires', 'A', '130', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('14', 'Fortune de placement', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('140', 'Placement de capitaux', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1400', 'Titres à long terme', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1410', 'Participations', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1420', 'Prêts actifs à long terme', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1430', 'Hypothèques actives', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1440', 'Autres placements de capitaux', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('150', 'Immobilisations corporelles mobiles', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1500', 'Machines, unités de productions', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1509', 'Provision applicable pour perte de machines', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1510', 'Mobilier, installations', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1519', 'Provision applicable pour perte de mobilier', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1520', 'Machines de bureau, installations informatiques', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1529', 'Provision applicable pour perte de machines de bureau', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1530', 'Véhicules', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1539', 'Provision applicable pour perte de véhicules', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1540', 'Outils', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1549', 'Provision applicable pour perte d\'outils', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1550', 'Installations d\'entrepôt', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1559', 'Provision applicable pour perte d\'installations d\'entrepôt', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('160', 'Immobilisations corporelles immobiles', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1600', 'Immobilier', 'A', '160', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1609', 'Provision applicable pour perte d\'immobilier', 'A', '160', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('170', 'Valeurs immatérielles', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1700', 'Brevets', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1709', 'Provision applicable pour perte de brevets', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1710', 'Marques', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1719', 'Provision applicable pour perte de marques', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1720', 'Licences', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1729', 'Provision applicable pour perte de licences', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2', 'PASSIFS', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('20', 'Fonds étrangers à court terme', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2000', 'Créanciers', 'A', '20', 'L', 'AP');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2011', 'TVA 2.5 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2012', 'TVA 3.8 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2013', 'TVA 8.0 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2020', 'Créanciers assurances sociales', 'A', '20', 'L', 'AP');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2030', 'Paiements antinicpés des clients', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2100', 'Banque compte courant', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2110', 'Effets à payer', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2120', 'Emprunts à court terme', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2200', 'Dividendes, tantièmes', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2300', 'Passifs transitoires', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2310', 'Provisions à court terme', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('24', 'Fonds étrangers à long terme', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2400', 'Emprunts à long terme', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2410', 'Hypothèques', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2460', 'Emprunt par obligations', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2600', 'Provisions à long terme', 'A', '260', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('28', 'Fonds propres', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('280', 'Capital de base', 'H', '28', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2800', 'Capital-actions', 'A', '280', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2810', 'Capital-participation', 'A', '280', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('290', 'Réserves, bénéfices au bilan', 'H', '28', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2900', 'Réserves légales', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2910', 'Autres réserves', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2990', 'Report du bénéfice/des pertes', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2995', 'Bénéfice annuel', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3', 'RENDEMENT PROVENANT DES LIVRAISONS ET DES PRESTATIONS', 'H', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3000', 'Rendement des ventes de produits', 'A', '3', 'I', 'AR_amount:IC_sale');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3090', 'Changements de position pour produits finis et semi-fabriqués', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3200', 'Rendement de la marchandise', 'A', '3', 'I', 'AR_amount:IC_sale');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3400', 'Rendement des services', 'A', '3', 'I', 'AR_amount:IC_income');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3600', 'Autres rendements', 'A', '3', 'I', 'AR_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3900', 'Pertes sur débiteurs', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3950', 'Perte sur taux de change', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3955', 'Bénéfice sur taux de change', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4', 'CHARGES DE MARCHANDISES ET DE MATÉRIEL', 'H', '4', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4000', 'Charges de matériel', 'A', '4', 'E', 'IC_cogs');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4200', 'Charges de marchandises', 'A', '4', 'E', 'IC_cogs');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4400', 'Dépenses pour services', 'A', '4', 'E', 'IC_expense');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5', 'CHARGES DU PERSONNEL', 'H', '5', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5000', 'Salaires', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5700', 'Prestations sociales', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5800', 'Charges restantes', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6', 'AUTRES CHARGES', 'H', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6000', 'Locaux', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6100', 'Entretien et réparations', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6200', 'Frais de véhicules', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6300', 'Frais d\'assurances', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6400', 'Frais d\'énergie et d\'élimination', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6500', 'Frais de gestion', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6600', 'Frais publicitaires', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6700', 'Autres charges d\'entreprise ', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6800', 'Charges d\'intérêts financières', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6850', 'Produit des intérêts financières', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6900', 'Amortissements', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7', 'AUTRES RÉSULTATS D\'ENTREPRISE', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('74', 'Résultat financier', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7400', 'Produit des intérêts', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7410', 'Charges d\'intérêts', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7420', 'Produit des titres', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7430', 'Coût des titres ', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7440', 'Produit des participations', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7450', 'Coût des participations', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('75', 'Résultat immobilier', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7500', 'Produit des immeubles', 'A', '75', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7510', 'Charges immobilières', 'A', '75', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8', 'RÉSULTAT NEUTRE, IMPÔTS', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('80', 'Résultat extraordinaire', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8000', 'Bénéfices extraordinaires', 'A', '80', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8010', 'Charges extraordinaires', 'A', '80', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('82', 'Résultat hors exploitation', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8200', 'Produit hors exploitation', 'A', '82', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8210', 'Charges hors exploitation', 'A', '82', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('89', 'Impôts', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8900', 'Impôts', 'A', '89', 'I', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9', 'CLÔTURE', 'H', '9', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9000', 'Compte de résultat', 'A', '9', 'I', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9100', 'Bilan', 'A', '9', 'I', 'AP_amount');
--
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1171'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1172'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1173'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1174'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2011'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2012'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2013'),0.080);
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '3200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '4200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '3950'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '3955'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, precision) VALUES (1,'CHF',2);
INSERT INTO curr (rn, curr, precision) VALUES (2,'EUR',2);
INSERT INTO curr (rn, curr, precision) VALUES (3,'USD',2);
