-- Swiss Italian chart of accounts UTF-8
-- Sistema dei conti svizzero per piccole e medie imprese nell’ambito
-- della produzione, del commercio e dei servizi
--
-- Tekki, 2012-02-12
--
SET client_encoding = 'UTF-8';
--
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1', 'ATTIVI', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('10', 'Attivo circolante', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('100', 'Mezzi liquidi', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1000', 'Cassa', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1010', 'Posta', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1020', 'Banca', 'A', '100', 'A', 'AR_paid:AP_paid');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1040', 'Assegni, cambiali attive', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1050', 'Investimento di fondi a breve scadenza', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1060', 'Titoli a breve scadenza', 'A', '100', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('110', 'Crediti', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1100', 'Debitori', 'A', '110', 'A', 'AR');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1109', 'Delcredere', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1130', 'Prestiti attivi a breve scadenza', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1140', 'Pagamenti anticipati a fornitori', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1171', 'IVA imposta precedente spese 2.5 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1172', 'IVA imposta precedente spese 3.8 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1173', 'IVA imposta precedente spese 8.0 %', 'A', '110', 'A', 'AP_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1174', 'IVA imposta precedente investimenti 8.0 %', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1176', 'Imposta preventiva', 'A', '110', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('120', 'Scorte', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1200', 'Merci commerciali', 'A', '120', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1210', 'Materie prime', 'A', '120', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1220', 'Prodotti finiti', 'A', '120', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1280', 'Lavori avviati', 'A', '120', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('130', 'Attivi transitori', 'H', '10', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1300', 'Attivi transitori', 'A', '130', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('14', 'Patrimonio investito', 'H', '1', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('140', 'Investimenti finanziari', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1400', 'Titoli de credito a lunga scadenza', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1410', 'Partecipazioni', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1420', 'Prestiti attivi a lunga scadenza', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1430', 'Ipoteche attive', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1440', 'Altri investimenti finanziari', 'A', '140', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('150', 'Investimenti materiali mobili', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1500', 'Macchinari, impianti di produzione', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1509', 'Rettifiche di valore macchinari', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1510', 'Mobilio, installazioni', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1519', 'Rettifiche di valore mobilio', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1520', 'Informatici', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1529', 'Rettifiche di valore informatici', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1530', 'Veicoli', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1539', 'Rettifiche di valore veicoli', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1540', 'Utensili', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1549', 'Rettifiche di valore utensili', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1550', 'Installazioni di magazzino', 'A', '150', 'A', 'IC');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1559', 'Rettifiche di valore installazioni di magazzino', 'A', '150', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('160', 'Investimenti materiali immobili', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1600', 'Immobili', 'A', '160', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1609', 'Rettifiche di valore immobili', 'A', '160', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('170', 'Investimenti non materiali', 'H', '14', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1700', 'Brevetti', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1709', 'Rettifiche di valore brevetti', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1710', 'Marchi', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1719', 'Rettifiche di valore marchi', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('1720', 'Licenze', 'A', '170', 'A', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link, contra) VALUES ('1729', 'Rettifiche di valore licenze', 'A', '170', 'A', '', '1');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2', 'PASSIVI', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('20', 'Capitale die terzi a breve scadenza', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2000', 'Creditori', 'A', '20', 'L', 'AP');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2011', 'IVA 2.5 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2012', 'IVA 3.8 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2013', 'IVA 8.0 %', 'A', '20', 'L', 'AR_tax:IC_taxpart:IC_taxservice');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2020', 'Creditori assicurazioni sociali', 'A', '20', 'L', 'AP');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2030', 'Pagamenti in anticipo di clienti', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2100', 'Banca conto corrente', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2110', 'Cambialo passive', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2120', 'Prestiti a breve scadenza', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2200', 'Dividendi, tantième', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2300', 'Passivi transitori', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2310', 'Accantonamenti a breve scadenza', 'A', '20', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('24', 'Capitale di terzi a lunga scadenza', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2400', 'Prestiti a lunga scadenza', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2410', 'Ipoteche', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2460', 'Prestiti obbligazionari', 'A', '240', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2600', 'Accantonamenti a lunga scadenza', 'A', '260', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('28', 'Capitale proprio', 'H', '2', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('280', 'Capitale di base', 'H', '28', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2800', 'Capitale azionario/socziale', 'A', '280', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2810', 'Capitale di partezipazione', 'A', '280', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('290', 'Riserve, utile di bilancio', 'H', '28', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2900', 'Riserve legali', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2910', 'Altre riserve', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2990', 'Utile riportato / perdita riportata', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('2995', 'Utile annuo', 'A', '290', 'L', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3', 'PROFITTO AZIENDALE DA CONSEGNE E PRESTAZIONI', 'H', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3000', 'Profitto da vendita di prodotti', 'A', '3', 'I', 'AR_amount:IC_sale');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3090', 'Modifiche delle scorte di prodotti finite e semifabbricati', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3200', 'Profitto da merci', 'A', '3', 'I', 'AR_amount:IC_sale');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3400', 'Profitto da servizi', 'A', '3', 'I', 'AR_amount:IC_income');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3600', 'Altri profitti', 'A', '3', 'I', 'AR_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3900', 'Perdite sui crediti', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3950', 'Perdite di cambio', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('3955', 'Utile di cambio', 'A', '3', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4', 'SPESE DI MATERIALE E MERCI', 'H', '4', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4000', 'Spese di materiale', 'A', '4', 'E', 'IC_cogs');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4200', 'Spese di merci', 'A', '4', 'E', 'IC_cogs');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('4400', 'Spese per servizi', 'A', '4', 'E', 'IC_expense');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5', 'SPESE DI PERSONALE', 'H', '5', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5000', 'Spese salariali', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5700', 'Prestazioni sociali', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('5800', 'Altre spese di personale', 'A', '5', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6', 'ALTRE SPESE AZIENDALI', 'H', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6000', 'Spese per l\'uso di immobili', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6100', 'Manutenzione e riparazioni', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6200', 'Spese per l\'uso di veicoli', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6300', 'Spese assicurative', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6400', 'Spese di energia e di smaltimento dei rifiuti', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6500', 'Spese amministrative e IT', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6600', 'Spese pubblicitarie', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6700', 'Altre spese aziendali ', 'A', '6', 'E', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6800', 'Spese per interessi o oneri finanziari', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6850', 'Profitto da interessi o proventi finanziari', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('6900', 'Ammortamenti', 'A', '6', 'E', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7', 'PROFITTI AZIENDALI ACCESSORI', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('74', 'Provento finanziario', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7400', 'Profitto da interessi', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7410', 'Spese per interessi', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7420', 'Profitto da titoli', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7430', 'Spese per titoli', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7440', 'Profitto da partecipazione', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7450', 'Spese di partecipazione', 'A', '74', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('75', 'Ricavi da immobili', 'H', '7', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7500', 'Profitto da immobili', 'A', '75', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('7510', 'Spese immobiliari', 'A', '75', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8', 'Profitto straordinario, imposte', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('80', 'Provento straordinario', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8000', 'Profitto straordinario', 'A', '80', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8010', 'Spese straordinarie', 'A', '80', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('82', 'Provento estraneo alla ditta', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8200', 'Profitto estreaneo alla ditta', 'A', '82', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8210', 'Spese estranee alla ditta', 'A', '82', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('89', 'Imposte', 'H', '8', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('8900', 'Imposte', 'A', '89', 'I', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9', 'CHIUSURA', 'H', '9', 'I', '');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9000', 'Conto economico', 'A', '9', 'I', 'AP_amount');
INSERT INTO chart (accno, description, charttype, gifi_accno, category, link) VALUES ('9100', 'Bilancio', 'A', '9', 'I', 'AP_amount');
--
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1171'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1172'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1173'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '1174'),0.080);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2011'),0.025);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2012'),0.038);
INSERT INTO tax (chart_id,rate) VALUES ((SELECT id FROM chart WHERE accno = '2013'),0.080);
--
INSERT INTO defaults (fldname, fldvalue) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '3200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '4200'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '3950'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '3955'));
INSERT INTO defaults (fldname, fldvalue) VALUES ('weightunit', 'kg');
INSERT INTO defaults (fldname, fldvalue) VALUES ('precision', '2');
--
INSERT INTO curr (rn, curr, prec) VALUES (1,'CHF',2);
INSERT INTO curr (rn, curr, prec) VALUES (2,'EUR',2);
INSERT INTO curr (rn, curr, prec) VALUES (3,'USD',2);
